'use strict';const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');const ctx={TextEncoder,URL,console};ctx.globalThis=ctx;vm.createContext(ctx);for(const f of ['model.js','runtime.js','st.js','zip.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,'..',f),'utf8'),ctx);const C=ctx.NXST;
test('imports Sysmac TSV headers and string size',()=>{const v=C.importSysmac('Name\tData Type\tComment\nRun\tBOOL\tEstado\nBatch\tSTRING[80]\tLote');assert.equal(v.length,2);assert.equal(v[1].type,'STRING');assert.equal(v[1].stringLength,80);});
test('imports simple ST declarations',()=>{const v=C.importSysmac('Run : BOOL;\nSpeed : REAL;');assert.equal(Array.from(v,x=>x.name).join(','),'Run,Speed');});
test('unsupported variables remain imported but disabled',()=>{const v=C.importSysmac('Name;Data Type\nA;ARRAY[0..2] OF BOOL');assert.equal(v[0].expose,false);});
test('demo validates and HTML is self contained',()=>{const p=C.demoProject();assert.equal(C.validate(p).length,0);const h=C.buildRuntimeHTML(p);assert.match(h,/<!doctype html>/);assert.match(h,/\/api\/read/);assert.ok(!h.includes('<script src='));assert.ok([...h].every(ch=>ch.charCodeAt(0)<128));const script=h.match(/<script>([\s\S]*)<\/script>/)[1];assert.doesNotThrow(()=>new Function(script));});
test('ST contains standard Omron socket blocks and embedded chunks',()=>{const s=C.buildST(C.demoProject());for(const x of ['StringToAry','AryToString'])assert.match(s,new RegExp(x));const locals=C.localVariablesTSV();for(const x of ['SktTCPAccept','SktTCPRcv','SktTCPSend','SktClose'])assert.match(locals,new RegExp(x));assert.match(s,/GET \/api\/read/);assert.match(s,/POST \/api\/write/);});
test('package zip starts with local header and contains project',()=>{const o=C.exportPackage(C.demoProject());assert.equal(o.zip[0],0x50);assert.ok(o.files['WebHMI_Server.st']);assert.ok(o.files['project.nxst']);});

test('POC limits exposed variables to 32',()=>{const p=C.newProject();p.variables=Array.from({length:33},(_,i)=>({id:i+1,name:'V'+i,type:'BOOL',stringLength:255,comment:'',access:'R',expose:true,live:true,writeSupported:true}));assert.ok(C.validate(p).some(x=>x.includes('máximo 32')));});

test('local variable TSV matches Sysmac Internals column order without a header',()=>{const lines=C.localVariablesTSV().split(/\r?\n/);assert.ok(!lines[0].startsWith('Name\t'));for(const line of lines){const cols=line.split('\t');assert.equal(cols.length,7);assert.ok(cols[0]);assert.ok(cols[1]);}const first=lines[0].split('\t');assert.equal(first[0],'Web_State');assert.equal(first[1],'UINT');assert.equal(first[2],'0');assert.equal(first[3],'');assert.equal(first[4],'');assert.equal(first[5],'');assert.equal(first[6],'Estado servidor HTTP');});

test('Sysmac literals escape JavaScript dollar signs',()=>{const p=C.demoProject();const s=C.buildST(p);assert.match(s,/\?\$\$\//);assert.ok(!s.includes('?$/'));});

test('generated ST uses CONCAT for STRING assembly',()=>{const p=C.demoProject();const s=C.buildST(p);assert.match(s,/Web_ApiBody := CONCAT\(Web_ApiBody,/);assert.ok(!/Web_ApiBody := Web_ApiBody &/.test(s));});

test('external variable TSV references exposed global variables',()=>{const p=C.demoProject();const x=C.externalVariablesTSV(p).split(/\r?\n/);assert.equal(x.length,4);assert.equal(x[0],'Machine_Running\tBOOL');assert.ok(x.some(line=>line==='Process_Setpoint\tREAL'));const o=C.exportPackage(p);assert.ok(o.files['WebHMI_ExternalVariables.tsv']);});

test('REAL and LREAL display use decimal dot like input and PLC wire',()=>{const h=C.buildRuntimeHTML(C.demoProject());assert.match(h,/n\.toFixed\(d\):String\(v\)/);assert.doesNotMatch(h,/n\.toFixed\(d\)\.replace\("\.",","\)/);assert.match(h,/n\.entry\.value=fmt\(o,v,""\)/);assert.match(h,/body:item\.raw/);const script=h.match(/<script>([\s\S]*)<\/script>/)[1];assert.doesNotThrow(()=>new Function(script));});

test('button modes and REAL precision are exported to runtime',()=>{const p=C.demoProject();const h=C.buildRuntimeHTML(p);assert.match(h,/"actionMode":"set"/);assert.match(h,/"decimals":2/);assert.match(h,/mode==="toggle"/);assert.match(h,/toFixed\(d\)/);});

test('button binding requires BOOL and decimals stay within range',()=>{const p=C.demoProject();const button=p.screens[0].objects.find(o=>o.kind==='button');button.binding='Process_Setpoint';assert.ok(C.validate(p).some(x=>x.includes('requiere BOOL')));button.binding='Start_Request';const value=p.screens[0].objects.find(o=>o.kind==='value');value.decimals=7;assert.ok(C.validate(p).some(x=>x.includes('decimales')));});

test('responsive width defaults and validation are stable',()=>{const p=C.newProject();assert.equal(p.minDisplayWidth,480);assert.equal(p.maxDisplayWidth,1920);assert.equal(C.validate(p).filter(x=>x.includes('ancho mínimo')||x.includes('ancho máximo')).length,0);p.minDisplayWidth=2000;p.maxDisplayWidth=1000;assert.ok(C.validate(p).some(x=>x.includes('mínimo no puede superar')));});

test('runtime fits stage to browser width with min and max limits',()=>{const p=C.demoProject();p.minDisplayWidth=480;p.maxDisplayWidth=1600;const h=C.buildRuntimeHTML(p);assert.match(h,/"minDisplayWidth":480/);assert.match(h,/"maxDisplayWidth":1600/);assert.match(h,/id="viewport"/);assert.match(h,/function fitStage\(\)/);assert.match(h,/ResizeObserver/);assert.match(h,/target=Math\.max\(minW,Math\.min\(maxW,available\)\)/);});

test('multi-screen projects are embedded with navigation',()=>{const p=C.demoProject();const s=C.newScreen('Mantenimiento');s.objects.push(Object.assign(C.newObject('lamp'),{binding:'Machine_Running'}));p.screens.push(s);const h=C.buildRuntimeHTML(p);assert.match(h,/Mantenimiento/);assert.match(h,/showScreen/);assert.equal(C.validate(p).length,0);});

test('industrial widgets and images are supported',()=>{const p=C.demoProject();p.assets.push({id:'img1',name:'logo.png',data:'data:image/png;base64,AA=='});p.screens[0].objects.push(Object.assign(C.newObject('image'),{assetId:'img1'}));p.screens[0].objects.push(Object.assign(C.newObject('pump'),{binding:'Machine_Running'}));const h=C.buildRuntimeHTML(p);assert.match(h,/data:image\/png;base64,AA==/);assert.match(h,/industrial/);assert.equal(C.validate(p).length,0);});

test('alarms are evaluated in generated ST and returned by api read',()=>{const p=C.demoProject();const s=C.buildST(p);assert.match(s,/A1=1\$n/);assert.match(s,/Process_Level > REAL#90\.0/);assert.match(s,/A1=0\$n/);});

test('recipes compile into one PLC recipe CASE route',()=>{const p=C.demoProject();const s=C.buildST(p);assert.match(s,/POST \/api\/recipe\?/);assert.match(s,/Process_Setpoint := REAL#50\.0/);assert.match(s,/BAD RECIPE/);const h=C.buildRuntimeHTML(p);assert.match(h,/applyRecipe/);});

test('old one-screen object projects migrate',()=>{const p=C.newProject();const old={...p,objects:[C.newObject('text')]};delete old.screens;const n=C.normalize(old);assert.equal(n.screens.length,1);assert.equal(n.screens[0].objects.length,1);});

test('button can navigate to another screen without PLC variable',()=>{const p=C.demoProject();const second=C.newScreen('Manual');p.screens.push(second);const b=C.newObject('button');b.text='Ir Manual';b.actionType='navigate';b.targetScreenId=second.id;b.binding='';p.screens[0].objects.push(b);assert.equal(C.validate(p).filter(x=>x.includes('Ir Manual')).length,0);const h=C.buildRuntimeHTML(p);assert.match(h,/"actionType":"navigate"/);assert.match(h,new RegExp(second.id));assert.match(h,/showScreenById/);});

test('navigation button rejects missing target screen',()=>{const p=C.demoProject();const b=C.newObject('button');b.text='Ir';b.actionType='navigate';b.targetScreenId='missing';p.screens[0].objects.push(b);assert.ok(C.validate(p).some(x=>x.includes('pantalla destino')));});

test('image budgets are strict per image and project total',()=>{const p=C.demoProject();const mk=n=>'data:image/png;base64,'+Buffer.alloc(n).toString('base64');p.assets=[{id:'big',name:'big.png',data:mk(C.IMAGE_MAX_BYTES+1)}];assert.ok(C.validate(p).some(x=>x.includes('64 KB')));p.assets=Array.from({length:5},(_,i)=>({id:'i'+i,name:'i'+i+'.png',data:mk(60*1024)}));assert.ok(C.validate(p).some(x=>x.includes('256 KB')));});

test('export hard-blocks embedded HTML above 512 KB',()=>{const p=C.demoProject();p.screens[0].objects.push(Object.assign(C.newObject('text'),{text:'X'.repeat(C.HTML_MAX_BYTES)}));assert.throws(()=>C.exportPackage(p),/512 KB/);});

test('editor warns before image embedding and auto-optimizes to WebP',()=>{const app=fs.readFileSync(path.join(__dirname,'..','app.js'),'utf8');assert.match(app,/confirm\('La imagen se incrusta dentro del programa del NX/);assert.match(app,/async function optimizeImage/);assert.match(app,/image\/webp/);assert.match(app,/IMAGE_OPTIMIZE_MAX_DIM/);assert.match(app,/Imagen optimizada:/);});

test('image optimizer keeps conservative 1024 px ceiling',()=>{assert.equal(C.IMAGE_OPTIMIZE_MAX_DIM,1024);});

test('STRING can be RW input up to 512 bytes',()=>{const v=C.importSysmac('Name\tData Type\nText\tSTRING[80]')[0];assert.equal(v.writeSupported,true);v.access='RW';const p=C.newProject();p.variables=[v];const o=C.newObject('input');o.binding='Text';p.screens[0].objects.push(o);assert.equal(C.validate(p).length,0);const tooLong=C.importSysmac('Name\tData Type\nBig\tSTRING[600]')[0];assert.equal(tooLong.writeSupported,false);});

test('STRING write uses raw POST body and ST direct assignment',()=>{const p=C.newProject();const v=C.importSysmac('Name\tData Type\nText\tSTRING[80]')[0];v.access='RW';v.expose=true;p.variables=[v];const o=C.newObject('input');o.binding='Text';p.screens[0].objects.push(o);const h=C.buildRuntimeHTML(p);assert.match(h,/body:item\.raw/);assert.match(h,/Content-Type":"text\/plain;charset=UTF-8"/);assert.ok(!h.includes('&v="+encodeURIComponent'));const s=C.buildST(p);assert.match(s,/Text := Web_ValueText;/);assert.match(s,/Web_PosBody := FIND\(Web_RxText, '\$r\$n\$r\$n'\)/);assert.match(C.localVariablesTSV(),/Web_ValueText\tSTRING\[512\]/);});

test('runtime exposes alarm window with active count and list',()=>{const p=C.demoProject();const h=C.buildRuntimeHTML(p);assert.match(h,/id="alarmOpen"/);assert.match(h,/id="alarmWindow"/);assert.match(h,/id="alarmList"/);assert.match(h,/alarmCount\.textContent/);assert.match(h,/alarmbar\.onclick/);assert.match(h,/ACTIVA/);});

test('STRING recipes compile to escaped ST literals',()=>{const p=C.newProject();const v=C.importSysmac('Name\tData Type\nProduct\tSTRING[80]')[0];v.access='RW';v.expose=true;p.variables=[v];p.recipes=[{id:'r',name:'R',values:{Product:"Lote A"}}];const s=C.buildST(p);assert.match(s,/Product := 'Lote A';/);});

test('runtime text widgets keep editor left alignment',()=>{const h=C.buildRuntimeHTML(C.demoProject());assert.match(h,/\.text \.in\{justify-content:flex-start;text-align:left\}/);});

test('P0 editor includes local autosave and recovery protections',()=>{const app=fs.readFileSync(path.join(__dirname,'..','app.js'),'utf8');const html=fs.readFileSync(path.join(__dirname,'..','index.html'),'utf8');assert.match(app,/hmi-nx-st:p0:latest:v1/);assert.match(app,/P0_AUTOSAVE_MS=1500/);assert.match(app,/visibilitychange/);assert.match(app,/beforeunload/);assert.match(app,/pagehide/);assert.match(app,/p0ProtectReplace/);assert.match(app,/antes-abrir-archivo/);assert.match(app,/guardado-manual/);assert.match(app,/exportado-sysmac/);assert.match(html,/id="saveStatus"/);assert.match(html,/id="recoveryDialog"/);assert.match(html,/id="recoveryList"/);});

test('P0 keeps rolling local history and quota fallback',()=>{const app=fs.readFileSync(path.join(__dirname,'..','app.js'),'utf8');assert.match(app,/P0_HISTORY_MAX=3/);assert.match(app,/P0_HISTORY_MS=30000/);assert.match(app,/localStorage\.removeItem\(P0_HISTORY\)/);assert.match(app,/AUTOSAVE FALLÓ/);assert.match(app,/antes-recuperar/);});


test('runtime navigation uses one screen dropdown with adjacent alarms button',()=>{const p=C.demoProject();p.screens.push(C.newScreen('Mantenimiento'));const h=C.buildRuntimeHTML(p);assert.match(h,/<nav id="nav"[^>]*><label for="screenSelect">Pantalla<\/label><select id="screenSelect"[^>]*><\/select><button[^>]*id="alarmOpen"/);assert.match(h,/screenSelect\.onchange=\(\)=>showScreen/);assert.match(h,/screenSelect\.value=String\(screenIndex\)/);assert.match(h,/screenSelect\.append\(option\)/);assert.match(h,/alarmCount\.textContent/);assert.ok(h.indexOf('id="screenSelect"')<h.indexOf('id="alarmOpen"'));assert.ok([...h].every(ch=>ch.charCodeAt(0)<128));});

test('legacy BOOL visual widgets migrate to one status element',()=>{const p=C.newProject();for(const kind of ['lamp','motor','pump','valve','conveyor','sensor']){const o=C.newObject(kind);o.binding='Run';p.screens[0].objects.push(o)}p.variables=[{id:1,name:'Run',type:'BOOL',stringLength:255,comment:'',access:'R',expose:true,live:true,writeSupported:true}];const n=C.normalize(p);assert.ok(n.screens[0].objects.every(o=>o.kind==='status'));assert.deepEqual(Array.from(n.screens[0].objects,o=>o.symbolType),['lamp','motor','pump','valve','conveyor','sensor']);assert.equal(C.validate(n).length,0);});

test('new status element chooses its industrial drawing with one property',()=>{const p=C.newProject();p.variables=[{id:1,name:'Run',type:'BOOL',stringLength:255,comment:'',access:'R',expose:true,live:true,writeSupported:true}];const o=C.newObject('status');o.binding='Run';o.symbolType='valve';p.screens[0].objects.push(o);assert.equal(C.validate(p).length,0);const h=C.buildRuntimeHTML(p);assert.match(h,/"kind":"status"/);assert.match(h,/"symbolType":"valve"/);assert.match(h,/function makeStatus/);});

test('button feedback can use the same or another BOOL tag',()=>{const p=C.newProject();p.variables=[{id:1,name:'Cmd',type:'BOOL',stringLength:255,comment:'',access:'RW',expose:true,live:true,writeSupported:true},{id:2,name:'Running',type:'BOOL',stringLength:255,comment:'',access:'R',expose:true,live:true,writeSupported:true}];const b=C.newObject('button');b.binding='Cmd';b.feedbackBinding='Running';b.feedbackColorOff='#123456';b.feedbackColorOn='#abcdef';p.screens[0].objects.push(b);assert.equal(C.validate(p).length,0);const h=C.buildRuntimeHTML(p);assert.match(h,/"feedbackBinding":"Running"/);assert.match(h,/"feedbackColorOff":"#123456"/);assert.match(h,/"feedbackColorOn":"#abcdef"/);assert.match(h,/n\.button\.style\.backgroundColor=boolValue/);const x=C.externalVariablesTSV(p);assert.match(x,/Cmd\tBOOL/);assert.match(x,/Running\tBOOL/);});

test('button feedback rejects non-BOOL and unexposed tags',()=>{const p=C.newProject();p.variables=[{id:1,name:'Cmd',type:'BOOL',stringLength:255,comment:'',access:'RW',expose:true,live:true,writeSupported:true},{id:2,name:'Level',type:'REAL',stringLength:255,comment:'',access:'R',expose:true,live:true,writeSupported:true},{id:3,name:'Hidden',type:'BOOL',stringLength:255,comment:'',access:'R',expose:false,live:true,writeSupported:true}];const b=C.newObject('button');b.binding='Cmd';b.feedbackBinding='Level';p.screens[0].objects.push(b);assert.ok(C.validate(p).some(x=>x.includes('feedback requiere BOOL')));b.feedbackBinding='Hidden';assert.ok(C.validate(p).some(x=>x.includes('feedback debe estar expuesta')));});

test('editor toolbar exposes only one Estado BOOL visual tool',()=>{const html=fs.readFileSync(path.join(__dirname,'..','index.html'),'utf8');assert.match(html,/data-kind="status">Estado/);for(const k of ['lamp','motor','pump','valve','conveyor','sensor'])assert.ok(!html.includes('data-kind="'+k+'"'));const app=fs.readFileSync(path.join(__dirname,'..','app.js'),'utf8');assert.match(app,/Dibujo<select data-p="symbolType"/);assert.match(app,/Feedback BOOL<select data-p="feedbackBinding"/);assert.match(app,/feedbackColorOff/);assert.match(app,/feedbackColorOn/);});

test('saved legacy STRING variables regain RW capability on normalize',()=>{const p=C.newProject();p.variables=[{id:1,name:'Text',type:'STRING',stringLength:256,comment:'',access:'R',expose:true,live:true,writeSupported:false}];const n=C.normalize(p);assert.equal(n.variables[0].writeSupported,true);assert.equal(n.variables[0].access,'R');});

test('STRING above 512 bytes remains read-only after normalize',()=>{const p=C.newProject();p.variables=[{id:1,name:'BigText',type:'STRING',stringLength:600,comment:'',access:'R',expose:true,live:true,writeSupported:true}];const n=C.normalize(p);assert.equal(n.variables[0].writeSupported,false);});

test('image can switch OFF ON assets from an exposed BOOL',()=>{const p=C.newProject();p.variables=[{id:1,name:'ShowAlt',type:'BOOL',stringLength:255,comment:'',access:'R',expose:true,live:true,writeSupported:true}];p.assets=[{id:'off',name:'off.png',data:'data:image/png;base64,AA=='},{id:'on',name:'on.png',data:'data:image/png;base64,AQ=='}];const o=C.newObject('image');o.assetId='off';o.assetOnId='on';o.binding='ShowAlt';p.screens[0].objects.push(o);assert.equal(C.validate(p).length,0);const h=C.buildRuntimeHTML(p);assert.match(h,/"assetId":"off"/);assert.match(h,/"assetOnId":"on"/);assert.match(h,/o\.kind==="image"&&n\.image&&o\.binding/);assert.match(h,/boolValue\(v\)\?\(o\.assetOnId\|\|o\.assetId\):o\.assetId/);const x=C.externalVariablesTSV(p);assert.match(x,/ShowAlt\tBOOL/);});

test('static image still works without a BOOL or ON asset',()=>{const p=C.newProject();p.assets=[{id:'one',name:'one.png',data:'data:image/png;base64,AA=='}];const o=C.newObject('image');o.assetId='one';p.screens[0].objects.push(o);assert.equal(C.validate(p).length,0);});

test('BOOL-switched image validates selector and TRUE asset',()=>{const p=C.newProject();p.variables=[{id:1,name:'Level',type:'REAL',stringLength:255,comment:'',access:'R',expose:true,live:true,writeSupported:true},{id:2,name:'Bit',type:'BOOL',stringLength:255,comment:'',access:'R',expose:false,live:true,writeSupported:true}];p.assets=[{id:'off',name:'off.png',data:'data:image/png;base64,AA=='}];const o=C.newObject('image');o.assetId='off';o.binding='Level';p.screens[0].objects.push(o);assert.ok(C.validate(p).some(x=>x.includes('requiere BOOL')));o.binding='Bit';assert.ok(C.validate(p).some(x=>x.includes('debe estar expuesta')));p.variables[1].expose=true;assert.ok(C.validate(p).some(x=>x.includes('TRUE/ON')));});

test('image properties expose BOOL OFF ON selectors and direct upload buttons',()=>{const app=fs.readFileSync(path.join(__dirname,'..','app.js'),'utf8');assert.match(app,/Variable BOOL \(opcional\)/);assert.match(app,/Imagen FALSE \/ OFF/);assert.match(app,/Imagen TRUE \/ ON/);assert.match(app,/id="uploadImageOff"/);assert.match(app,/id="uploadImageOn"/);assert.match(app,/imageUploadTarget/);assert.match(app,/assetOnId/);});

test('read protocol is atomic with SEQ and END markers',()=>{const s=C.buildST(C.demoProject());assert.match(s,/Web_Seq := Web_Seq \+ UDINT#1/);assert.match(s,/SEQ=/);assert.match(s,/END=/);assert.match(C.localVariablesTSV(),/Web_Seq\tUDINT\t0/);const h=C.buildRuntimeHTML(C.demoProject());assert.match(h,/function parseSnapshot/);assert.match(h,/seq===null\|\|end===null\|\|seq!==end/);assert.match(h,/tag ausente/);});

test('runtime communications are single-flight with timeout and backoff',()=>{const h=C.buildRuntimeHTML(C.demoProject());assert.match(h,/const comm=\{busy:false/);assert.match(h,/if\(comm\.busy\)return/);assert.match(h,/AbortController/);assert.match(h,/READ_TIMEOUT/);assert.match(h,/function backoff\(\)/);assert.match(h,/\[300,500,1000,2000,5000\]/);assert.match(h,/comm\.failures>=3\?"OFFLINE":"DEGRADED"/);assert.ok(!h.includes('setTimeout(poll'))});

test('runtime keeps last good snapshot and marks stale instead of clearing values',()=>{const h=C.buildRuntimeHTML(C.demoProject());assert.match(h,/SNAP_KEY="hminx:runtime:v2:/);assert.match(h,/saveGoodSnapshot/);assert.match(h,/loadCachedSnapshot/);assert.match(h,/stage\.classList\.toggle\("comm-stale",stale\)/);assert.match(h,/datos "\+age\+"s"/);});

test('writes are queued, retried only within TTL and confirmed by readback',()=>{const h=C.buildRuntimeHTML(C.demoProject());assert.match(h,/pendingWrites=new Map/);assert.match(h,/WRITE_TTL=5000/);assert.match(h,/MAX_WRITE_ATTEMPTS=3/);assert.match(h,/function confirmWrites/);assert.match(h,/sameValue\(tag,vals\[name\],item\.raw\)/);assert.match(h,/item\.state="retry"/);assert.match(h,/latest|pendingWrites\.set\(name/);assert.match(h,/No confirmado antes de caducar/);});

test('input Enter uses the same write path as Apply',()=>{const h=C.buildRuntimeHTML(C.demoProject());assert.match(h,/i\.addEventListener\("keydown",e=>\{if\(e\.key==="Enter"\)/);assert.match(h,/const send=\(\)=>\{if\(write\(o\.binding,i\.value,\{min:o\.inputMin,max:o\.inputMax,node:n\}\)\)/);});

test('numeric input hides native spinners and blinks while an edit is not submitted',()=>{const h=C.buildRuntimeHTML(C.demoProject());assert.match(h,/-moz-appearance:textfield/);assert.match(h,/::-webkit-inner-spin-button/);assert.match(h,/@keyframes input-dirty-blink/);assert.match(h,/i\.addEventListener\("input",\(\)=>\{n\.inputDirty=true/);assert.match(h,/classList\.toggle\("input-dirty",Boolean\(n\.inputDirty\)\)/);assert.match(h,/!n\.inputDirty&&document\.activeElement!==n\.entry/);assert.match(h,/if\(write\(o\.binding,i\.value,\{min:o\.inputMin,max:o\.inputMax,node:n\}\)\)\{n\.inputDirty=false;paint\(\)\}/);});

test('server ST includes a cycle watchdog recovery path',()=>{const s=C.buildST(C.demoProject());assert.match(s,/Web_StateTicks > Web_WatchdogLimit/);assert.match(s,/Web_State := UINT#90/);const vars=C.localVariablesTSV();assert.match(vars,/Web_PrevState\tUINT/);assert.match(vars,/Web_StateTicks\tUDINT/);assert.match(vars,/Web_WatchdogLimit\tUDINT\t5000/);});

test('recipes remain single-shot and are not automatically retried',()=>{const h=C.buildRuntimeHTML(C.demoProject());assert.match(h,/ERROR RECETA \| no reintentada/);assert.match(h,/if\(pendingRecipe\)/);assert.ok(!/retry.*recipe/i.test(h));});

test('active alarm strip stays inside navigation without vertical layout shift',()=>{const h=C.buildRuntimeHTML(C.demoProject());const nav=h.match(/<nav id="nav"[\s\S]*?<\/nav>/)?.[0]||'';assert.match(nav,/id="alarmOpen"/);assert.match(nav,/id="alarmbar"/);assert.ok(nav.indexOf('id="alarmOpen"')<nav.indexOf('id="alarmbar"'));assert.match(h,/#alarmbar\{height:38px[^}]*visibility:hidden/);assert.match(h,/#alarmbar\.show\{visibility:visible;cursor:pointer\}/);assert.doesNotMatch(h,/<\/nav><div id="alarmbar"/);});

test('numeric input supports optional negative minimum and maximum',()=>{const p=C.newProject();p.variables=[{id:1,name:'Setpoint',type:'REAL',stringLength:255,comment:'',access:'RW',expose:true,live:true,writeSupported:true}];const o=C.newObject('input');o.binding='Setpoint';o.inputMin=-25.5;o.inputMax=120;p.screens[0].objects.push(o);const n=C.normalize(p);assert.equal(n.screens[0].objects[0].inputMin,-25.5);assert.equal(n.screens[0].objects[0].inputMax,120);assert.equal(C.validate(n).length,0);const h=C.buildRuntimeHTML(n);assert.match(h,/"inputMin":-25\.5/);assert.match(h,/"inputMax":120/);assert.match(h,/i\.type="number"/);assert.match(h,/i\.min=String\(o\.inputMin\)/);assert.match(h,/i\.max=String\(o\.inputMax\)/);assert.match(h,/Valor menor que limite inferior/);assert.match(h,/Valor mayor que limite superior/);});

test('numeric input rejects inverted limits at project validation',()=>{const p=C.newProject();p.variables=[{id:1,name:'Setpoint',type:'INT',stringLength:255,comment:'',access:'RW',expose:true,live:true,writeSupported:true}];const o=C.newObject('input');o.binding='Setpoint';o.inputMin=10;o.inputMax=-10;p.screens[0].objects.push(o);assert.ok(C.validate(p).some(x=>x.includes('límite inferior no puede superar')));});

test('STRING input ignores numeric limits and remains text input',()=>{const p=C.newProject();p.variables=[{id:1,name:'Text',type:'STRING',stringLength:80,comment:'',access:'RW',expose:true,live:true,writeSupported:true}];const o=C.newObject('input');o.binding='Text';o.inputMin=-5;o.inputMax=5;p.screens[0].objects.push(o);assert.equal(C.validate(p).filter(x=>x.includes('límite')).length,0);const h=C.buildRuntimeHTML(p);assert.match(h,/tag&&tag\.type==="STRING"\)\{i\.type="text"/);});

test('built-in state symbols provide distinct OFF and ON SVGs',()=>{for(const type of ['lamp','motor','pump','valve','conveyor','sensor']){const off=C.statusSvg(type,false),on=C.statusSvg(type,true);assert.match(off,/^<svg /);assert.match(on,/^<svg /);assert.notEqual(off,on);assert.match(off,/#475569/);assert.match(on,/#15803d/);}});

test('status widget can map visual ON to TRUE or FALSE',()=>{const p=C.newProject();p.variables=[{id:1,name:'Run',type:'BOOL',stringLength:255,comment:'',access:'R',expose:true,live:true,writeSupported:true}];const o=C.newObject('status');o.binding='Run';o.symbolType='pump';o.stateOnWhen='false';p.screens[0].objects.push(o);assert.equal(C.validate(p).length,0);const h=C.buildRuntimeHTML(p);assert.match(h,/"stateOnWhen":"false"/);assert.match(h,/visualOn=boolValue\(v\)===\(o\.stateOnWhen!=="false"\)/);assert.match(h,/statusSvg\(o\.symbolType\|\|"lamp",visualOn\)/);});

test('editor exposes state OFF ON previews and numeric input limit fields',()=>{const app=fs.readFileSync(path.join(__dirname,'..','app.js'),'utf8');assert.match(app,/Estado ON cuando BOOL =/);assert.match(app,/class="state-pair"/);assert.match(app,/C\.statusSvg\(o\.symbolType,false\)/);assert.match(app,/C\.statusSvg\(o\.symbolType,true\)/);assert.match(app,/data-p="inputMin"/);assert.match(app,/data-p="inputMax"/);assert.match(app,/Se admiten valores negativos/);});

test('editor supports context menu and keyboard widget copy paste',()=>{const app=fs.readFileSync(path.join(__dirname,'..','app.js'),'utf8'),html=fs.readFileSync(path.join(__dirname,'..','index.html'),'utf8'),css=fs.readFileSync(path.join(__dirname,'..','style.css'),'utf8');assert.match(app,/function copyWidget\(\)/);assert.match(app,/function pasteWidget\(\)/);assert.match(app,/o\.id=C\.id\(\)/);assert.match(app,/n\.oncontextmenu=e=>showWidgetMenu\(e,o\.id\)/);assert.match(app,/key==='c'/);assert.match(app,/key==='v'/);assert.match(app,/input,textarea,select,\[contenteditable\]/);assert.match(html,/id="widgetMenu"/);assert.match(css,/widget-menu\[hidden\]/);});
