'use strict';const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');const ctx={TextEncoder,URL,console};ctx.globalThis=ctx;vm.createContext(ctx);for(const f of ['model.js','runtime.js','st.js','zip.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,'..',f),'utf8'),ctx);const C=ctx.NXST;
test('imports Sysmac TSV headers and string size',()=>{const v=C.importSysmac('Name\tData Type\tComment\nRun\tBOOL\tEstado\nBatch\tSTRING[80]\tLote');assert.equal(v.length,2);assert.equal(v[1].type,'STRING');assert.equal(v[1].stringLength,80);});
test('imports simple ST declarations',()=>{const v=C.importSysmac('Run : BOOL;\nSpeed : REAL;');assert.equal(Array.from(v,x=>x.name).join(','),'Run,Speed');});
test('unsupported variables remain imported but disabled',()=>{const v=C.importSysmac('Name;Data Type\nA;ARRAY[0..2] OF BOOL');assert.equal(v[0].expose,false);});
test('demo validates and HTML is self contained',()=>{const p=C.demoProject();assert.equal(C.validate(p).length,0);const h=C.buildRuntimeHTML(p);assert.match(h,/<!doctype html>/);assert.match(h,/\/api\/read/);assert.ok(!h.includes('<script src='));assert.ok([...h].every(ch=>ch.charCodeAt(0)<128));const script=h.match(/<script>([\s\S]*)<\/script>/)[1];assert.doesNotThrow(()=>new Function(script));});
test('ST contains standard Omron socket blocks and embedded chunks',()=>{const s=C.buildST(C.demoProject());for(const x of ['StringToAry','AryToString'])assert.match(s,new RegExp(x));const locals=C.localVariablesTSV();for(const x of ['SktTCPAccept','SktTCPRcv','SktTCPSend','SktClose'])assert.match(locals,new RegExp(x));assert.match(s,/GET \/api\/read/);assert.match(s,/POST \/api\/write/);});
test('package zip starts with local header and contains project',()=>{const o=C.exportPackage(C.demoProject());assert.equal(o.zip[0],0x50);assert.ok(o.files['WebHMI_Server.st']);assert.ok(o.files['project.nxst']);});

test('POC limits exposed variables to 32',()=>{const p=C.newProject();p.variables=Array.from({length:33},(_,i)=>({id:i+1,name:'V'+i,type:'BOOL',stringLength:255,comment:'',access:'R',expose:true,live:true,writeSupported:true}));assert.ok(C.validate(p).some(x=>x.includes('máximo 32')));});

test('local variable TSV matches Sysmac Internals column order without a header',()=>{const lines=C.localVariablesTSV().split(/\r?\n/);assert.ok(!lines[0].startsWith('Name\t'));for(const line of lines){const cols=line.split('\t');assert.equal(cols.length,7);assert.ok(cols[0]);assert.ok(cols[1]);}const first=lines[0].split('\t');assert.equal(first[0],'Web_State');assert.equal(first[1],'UINT');assert.equal(first[2],'0');assert.equal(first[3],'');assert.equal(first[4],'');assert.equal(first[5],'');});
