(function(){
'use strict';const C=NXST,$=s=>document.querySelector(s);let p=C.demoProject(),selected=null,drag=null,screenId=p.screens[0].id;
const NUM=v=>C.NUMERIC_TYPES.has(v.type),BOOL=v=>v.type==='BOOL';
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2200)}
function activeScreen(){return p.screens.find(s=>s.id===screenId)||p.screens[0]}
function syncProjectInputs(){p.name=$('#projectName').value.trim()||'WebHMI ST';p.port=Number($('#port').value);p.pollMs=Number($('#pollMs').value);p.width=Number($('#screenW').value);p.height=Number($('#screenH').value);p.minDisplayWidth=Number($('#minDisplayWidth').value);p.maxDisplayWidth=Number($('#maxDisplayWidth').value);}
function render(){p=C.normalize(p);if(!p.screens.some(s=>s.id===screenId))screenId=p.screens[0].id;$('#projectName').value=p.name;$('#port').value=p.port;$('#pollMs').value=p.pollMs;$('#screenW').value=p.width;$('#screenH').value=p.height;$('#minDisplayWidth').value=p.minDisplayWidth;$('#maxDisplayWidth').value=p.maxDisplayWidth;renderScreens();renderVars();renderCanvas();renderProps();renderAlarms();renderRecipes();renderDiag();}
function renderScreens(){const sel=$('#screenSelect');sel.innerHTML=p.screens.map(s=>`<option value="${s.id}" ${s.id===screenId?'selected':''}>${C.esc(s.name)}</option>`).join('');$('#deleteScreen').disabled=p.screens.length<=1;}
function renderVars(){const live=p.variables.filter(v=>v.expose&&v.live).length;$('#varSummary').textContent=`${p.variables.length} importadas · ${live} expuestas`;$('#varList').innerHTML=p.variables.map((v,i)=>`<div class="var-row ${v.live?'':'bad'}"><input type="checkbox" data-exp="${i}" ${v.expose?'checked':''} ${v.live?'':'disabled'}><code title="${C.esc(v.comment)}">${C.esc(v.name)}</code><span>${C.esc(v.type)}</span><select data-acc="${i}" ${v.writeSupported?'':'disabled'}><option value="R" ${v.access==='R'?'selected':''}>R</option><option value="RW" ${v.access==='RW'?'selected':''}>RW</option></select></div>`).join('')||'<p class="hint" style="padding:8px">Importa variables.</p>';document.querySelectorAll('[data-exp]').forEach(x=>x.onchange=()=>{p.variables[+x.dataset.exp].expose=x.checked;renderDiag();});document.querySelectorAll('[data-acc]').forEach(x=>x.onchange=()=>{p.variables[+x.dataset.acc].access=x.value;renderProps();renderRecipes();renderDiag();});}
function previewShape(o){if(o.kind==='lamp')return '<div class="inner"></div>';if(o.kind==='bar')return '<div class="track"><div class="fill"></div></div>';if(o.kind==='image'){const a=p.assets.find(a=>a.id===o.assetId);return a?'<img src="'+a.data+'" alt="">':'<div class="inner">Imagen</div>';}if(['motor','pump','valve','tank','conveyor','sensor'].includes(o.kind))return '<div class="symbol">'+(o.kind==='tank'?'<div class="level"></div>':'')+'</div><div class="caption">'+C.esc(o.text||o.kind)+'</div>';return '<div class="inner">'+C.esc(o.text||o.kind)+'</div>';}
function renderCanvas(){const s=activeScreen(),c=$('#canvas');c.className='canvas';c.style.width=p.width+'px';c.style.height=p.height+'px';$('#canvasInfo').textContent=`${p.width}×${p.height} · ${s.objects.length} objetos`;c.innerHTML='';for(const o of s.objects){const n=document.createElement('div');n.className='widget '+o.kind+(['motor','pump','valve','tank','conveyor','sensor'].includes(o.kind)?' industrial':'')+(selected===o.id?' selected':'');n.dataset.id=o.id;Object.assign(n.style,{left:o.x+'px',top:o.y+'px',width:o.w+'px',height:o.h+'px'});n.innerHTML=previewShape(o);n.onpointerdown=e=>{if(e.button!==0)return;selected=o.id;drag={id:o.id,x:e.clientX,y:e.clientY,ox:o.x,oy:o.y};n.setPointerCapture(e.pointerId);renderProps();document.querySelectorAll('.widget').forEach(z=>z.classList.toggle('selected',z.dataset.id===o.id));};n.onpointermove=e=>{if(!drag||drag.id!==o.id)return;o.x=Math.max(0,Math.min(p.width-o.w,drag.ox+e.clientX-drag.x));o.y=Math.max(0,Math.min(p.height-o.h,drag.oy+e.clientY-drag.y));n.style.left=o.x+'px';n.style.top=o.y+'px';};n.onpointerup=()=>{drag=null;renderProps();};c.append(n);}c.onclick=e=>{if(e.target===c){selected=null;renderProps();document.querySelectorAll('.widget').forEach(z=>z.classList.remove('selected'));}};}
function opts(value,filter=()=>true){return '<option value="">— variable —</option>'+p.variables.filter(v=>v.live&&filter(v)).map(v=>`<option value="${C.esc(v.name)}" ${v.name===value?'selected':''}>${C.esc(v.name)} · ${v.type} · ${v.access}</option>`).join('');}
function renderProps(){const host=$('#properties'),o=activeScreen().objects.find(o=>o.id===selected);if(!o){host.innerHTML='<p class="hint">Selecciona un elemento.</p>';return;}const filter=v=>['lamp','motor','pump','valve','conveyor','sensor','button'].includes(o.kind)?BOOL(v):['bar','tank','input'].includes(o.kind)?NUM(v):true;let extra='';if(o.kind==='button')extra+=`<label>Acción<select data-p="actionMode"><option value="set" ${o.actionMode==='set'?'selected':''}>SET</option><option value="reset" ${o.actionMode==='reset'?'selected':''}>RESET</option><option value="toggle" ${o.actionMode==='toggle'?'selected':''}>TOGGLE</option></select></label>`;if(['value','input'].includes(o.kind))extra+=`<label>Decimales<input data-p="decimals" type="number" min="0" max="6" value="${o.decimals}"></label>`;if(['bar','tank'].includes(o.kind))extra+=`<div class="grid2"><label>Mín<input data-p="min" type="number" value="${o.min}"></label><label>Máx<input data-p="max" type="number" value="${o.max}"></label></div>`;if(o.kind==='image')extra+=`<label>Imagen<select data-p="assetId"><option value="">— imagen —</option>${p.assets.map(a=>`<option value="${a.id}" ${a.id===o.assetId?'selected':''}>${C.esc(a.name)}</option>`).join('')}</select></label>`;host.innerHTML=`<label>Tipo<input value="${o.kind}" disabled></label><label>Texto<input data-p="text" value="${C.esc(o.text)}"></label>${!['text','image'].includes(o.kind)?`<label>Variable<select data-p="binding">${opts(o.binding,filter)}</select></label>`:''}${extra}<div class="grid2"><label>X<input data-p="x" type="number" value="${Math.round(o.x)}"></label><label>Y<input data-p="y" type="number" value="${Math.round(o.y)}"></label><label>Ancho<input data-p="w" type="number" value="${o.w}"></label><label>Alto<input data-p="h" type="number" value="${o.h}"></label></div><button id="deleteObj" class="delete">Eliminar</button>`;host.querySelectorAll('[data-p]').forEach(x=>x.onchange=()=>{let v=x.value;if(['x','y','w','h','min','max','decimals'].includes(x.dataset.p))v=Number(v);o[x.dataset.p]=v;if(x.dataset.p==='binding'&&v){const tag=p.variables.find(t=>t.name===v);tag.expose=true;if(['button','input'].includes(o.kind)&&tag.writeSupported)tag.access='RW';}render();});$('#deleteObj').onclick=()=>{activeScreen().objects=activeScreen().objects.filter(x=>x!==o);selected=null;render();};}
function renderAlarms(){const host=$('#alarmEditor');host.innerHTML=p.alarms.map((a,i)=>`<div class="editor-card"><input data-alarm="${i}" data-k="name" value="${C.esc(a.name)}"><select data-alarm="${i}" data-k="binding">${opts(a.binding)}</select><div class="grid3"><select data-alarm="${i}" data-k="operator"><option value="eq" ${a.operator==='eq'?'selected':''}>=</option><option value="ne" ${a.operator==='ne'?'selected':''}>≠</option><option value="gt" ${a.operator==='gt'?'selected':''}>&gt;</option><option value="ge" ${a.operator==='ge'?'selected':''}>≥</option><option value="lt" ${a.operator==='lt'?'selected':''}>&lt;</option><option value="le" ${a.operator==='le'?'selected':''}>≤</option></select><input data-alarm="${i}" data-k="value" value="${C.esc(a.value)}"><select data-alarm="${i}" data-k="severity"><option value="info" ${a.severity==='info'?'selected':''}>Info</option><option value="warning" ${a.severity==='warning'?'selected':''}>Aviso</option><option value="high" ${a.severity==='high'?'selected':''}>Alta</option></select></div><button data-del-alarm="${i}">Eliminar</button></div>`).join('')||'<p class="hint">Sin alarmas.</p>';host.querySelectorAll('[data-alarm]').forEach(x=>x.onchange=()=>{const a=p.alarms[+x.dataset.alarm];a[x.dataset.k]=x.value;if(x.dataset.k==='binding'){const v=p.variables.find(v=>v.name===x.value);if(v)v.expose=true;}renderDiag();});host.querySelectorAll('[data-del-alarm]').forEach(x=>x.onclick=()=>{p.alarms.splice(+x.dataset.delAlarm,1);render();});}
function recipeText(r){return Object.entries(r.values||{}).map(([k,v])=>k+'='+v).join('\n')}
function parseRecipeText(t){const out={};for(const line of t.split(/\r?\n/)){if(!line.trim())continue;const k=line.indexOf('=');if(k<1)continue;const name=line.slice(0,k).trim(),raw=line.slice(k+1).trim(),v=p.variables.find(v=>v.name===name);if(!v)throw new Error('Variable de receta no encontrada: '+name);if(v.access!=='RW'||!v.writeSupported)throw new Error(name+' debe ser RW');out[name]=C.typedFor(v,raw);}return out}
function renderRecipes(){const host=$('#recipeEditor');host.innerHTML=p.recipes.map((r,i)=>`<div class="editor-card"><input data-recipe-name="${i}" value="${C.esc(r.name)}"><textarea data-recipe-values="${i}" rows="4">${C.esc(recipeText(r))}</textarea><button data-del-recipe="${i}">Eliminar</button></div>`).join('')||'<p class="hint">Sin recetas.</p>';host.querySelectorAll('[data-recipe-name]').forEach(x=>x.onchange=()=>{p.recipes[+x.dataset.recipeName].name=x.value;renderDiag();});host.querySelectorAll('[data-recipe-values]').forEach(x=>x.onchange=()=>{try{p.recipes[+x.dataset.recipeValues].values=parseRecipeText(x.value);renderDiag();}catch(e){toast(e.message)}});host.querySelectorAll('[data-del-recipe]').forEach(x=>x.onclick=()=>{p.recipes.splice(+x.dataset.delRecipe,1);render();});}
function renderDiag(){syncProjectInputs();const errors=C.validate(p),html=C.buildRuntimeHTML(p),bytes=new TextEncoder().encode(html).length;let list=[`<div class="diagnostic ${errors.length?'error':'ok'}">${errors.length?'Bloqueos: '+errors.length:'Proyecto exportable'}</div>`];for(const e of errors.slice(0,7))list.push(`<div class="diagnostic error">${C.esc(e)}</div>`);list.push(`<div class="diagnostic">HTML: ${(bytes/1024).toFixed(1)} KB · ${p.screens.length} pantallas · ${p.assets.length} imágenes · ${p.alarms.length} alarmas · ${p.recipes.length} recetas.</div>`);list.push('<div class="diagnostic ok">Base servidor/lectura validada en NX102 real.</div>');if(bytes>700*1024)list.push('<div class="diagnostic warn">HTML >700 KB: medir memoria y tiempo de transferencia.</div>');$('#diagnostics').innerHTML=list.join('');}
function importText(text){const old=new Map(p.variables.map(v=>[v.name,v]));const vars=C.importSysmac(text);for(const v of vars){const prev=old.get(v.name);if(prev){v.access=prev.access;v.expose=prev.expose;}}p.variables=vars;render();toast(vars.length+' variables importadas');}
function download(name,data,type='application/octet-stream'){const a=document.createElement('a'),blob=new Blob([data],{type});a.href=URL.createObjectURL(blob);a.download=name;document.body.append(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},500);}
function preview(){syncProjectInputs();const errors=C.validate(p);if(errors.length){toast('Corrige bloqueos antes de previsualizar');return;}let html=C.buildRuntimeHTML(p);html=html.replace('showScreen(0);fitStage();poll();</script>','for(const v of P.vars)vals[v.name]=v.type==="BOOL"?false:55;document.getElementById("status").textContent="PREVIEW local";showScreen(0);fitStage();paint();</script>');$('#previewFrame').srcdoc=html;$('#previewDialog').showModal();}
document.querySelectorAll('.tool-grid [data-kind]').forEach(b=>b.onclick=()=>{const o=C.newObject(b.dataset.kind);activeScreen().objects.push(o);selected=o.id;render();});
['projectName','port','pollMs','screenW','screenH','minDisplayWidth','maxDisplayWidth'].forEach(id=>$('#'+id).onchange=()=>{syncProjectInputs();renderCanvas();renderDiag();});
$('#screenSelect').onchange=e=>{screenId=e.target.value;selected=null;render();};$('#addScreen').onclick=()=>{const s=C.newScreen('Pantalla '+(p.screens.length+1));p.screens.push(s);screenId=s.id;selected=null;render();};$('#deleteScreen').onclick=()=>{if(p.screens.length<=1)return;p.screens=p.screens.filter(s=>s.id!==screenId);screenId=p.screens[0].id;selected=null;render();};
$('#imageBtn').onclick=()=>$('#imageFile').click();$('#imageFile').onchange=async e=>{const file=e.target.files[0];if(!file)return;if(file.size>800*1024){toast('Imagen demasiado grande para HMI embebida (>800 KB)');e.target.value='';return;}const data=await new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)});const asset={id:C.id(),name:file.name,data};p.assets.push(asset);const o=C.newObject('image');o.assetId=asset.id;o.text=file.name;activeScreen().objects.push(o);selected=o.id;e.target.value='';render();};
$('#addAlarm').onclick=()=>{const v=p.variables.find(v=>v.live);p.alarms.push({id:C.id(),name:'Nueva alarma',binding:v?.name||'',operator:v?.type==='BOOL'?'eq':'gt',value:v?.type==='BOOL'?true:0,severity:'warning'});if(v)v.expose=true;render();};$('#addRecipe').onclick=()=>{p.recipes.push({id:C.id(),name:'Nueva receta',values:{}});render();};
$('#demoBtn').onclick=()=>{p=C.demoProject();screenId=p.screens[0].id;selected=null;render()};$('#newBtn').onclick=()=>{p=C.newProject();screenId=p.screens[0].id;selected=null;render()};
$('#importFileBtn').onclick=()=>$('#varsFile').click();$('#varsFile').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{importText(await file.text())}catch(err){toast(err.message)}e.target.value='';};$('#pasteBtn').onclick=()=>{$('#pasteText').value='';$('#pasteError').textContent='';$('#pasteDialog').showModal()};$('#pasteImport').onclick=()=>{try{importText($('#pasteText').value);$('#pasteDialog').close()}catch(e){$('#pasteError').textContent=e.message}};
$('#previewBtn').onclick=preview;$('#closePreview').onclick=()=>$('#previewDialog').close();$('#saveBtn').onclick=()=>{syncProjectInputs();download((p.name||'project').replace(/[^A-Za-z0-9_-]+/g,'_')+'.nxst',JSON.stringify(C.normalize(p),null,2),'application/json')};$('#loadBtn').onclick=()=>$('#projectFile').click();$('#projectFile').onchange=async e=>{try{p=C.normalize(JSON.parse(await e.target.files[0].text()));screenId=p.screens[0].id;selected=null;render();}catch(err){toast('Proyecto no válido: '+err.message)}e.target.value='';};$('#exportBtn').onclick=()=>{syncProjectInputs();try{const out=C.exportPackage(p),name=(p.name||'WebHMI_ST').replace(/[^A-Za-z0-9_-]+/g,'_')+'_Sysmac.zip';download(name,out.zip,'application/zip');toast('Paquete Sysmac generado')}catch(e){toast(e.message)}};
render();
})();