(function(){
'use strict';const C=NXST,$=s=>document.querySelector(s);let p=C.demoProject(),selected=null,drag=null;
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),1800)}
function syncProjectInputs(){p.name=$('#projectName').value.trim()||'WebHMI ST';p.port=Number($('#port').value);p.pollMs=Number($('#pollMs').value);p.width=Number($('#screenW').value);p.height=Number($('#screenH').value);}
function render(){
 $('#projectName').value=p.name;$('#port').value=p.port;$('#pollMs').value=p.pollMs;$('#screenW').value=p.width;$('#screenH').value=p.height;
 renderVars();renderCanvas();renderProps();renderDiag();
}
function renderVars(){const exposed=p.variables.filter(v=>v.expose).length,live=p.variables.filter(v=>v.expose&&v.live).length;$('#varSummary').textContent=`${p.variables.length} importadas · ${live} expuestas compatibles · ${exposed-live} incompatibles desactivadas`;
$('#varList').innerHTML=p.variables.map((v,i)=>`<div class='var-row ${v.live?'':'bad'}'><input type='checkbox' data-exp='${i}' ${v.expose?'checked':''} ${v.live?'':'disabled'}><code title='${C.esc(v.comment)}'>${C.esc(v.name)}</code><span>${C.esc(v.type)}${v.type==='STRING'?'['+v.stringLength+']':''}</span><select data-acc='${i}' ${v.writeSupported?'':'disabled'}><option value='R' ${v.access==='R'?'selected':''}>Lectura</option><option value='RW' ${v.access==='RW'?'selected':''}>Lectura + escritura</option></select></div>`).join('')||'<p class="hint" style="padding:8px">Importa variables para empezar.</p>';
 document.querySelectorAll('[data-exp]').forEach(x=>x.onchange=()=>{p.variables[+x.dataset.exp].expose=x.checked;renderDiag();});document.querySelectorAll('[data-acc]').forEach(x=>x.onchange=()=>{p.variables[+x.dataset.acc].access=x.value;renderCanvas();renderProps();renderDiag();});}
function renderCanvas(){const c=$('#canvas');c.className='canvas';c.style.width=p.width+'px';c.style.height=p.height+'px';$('#canvasInfo').textContent=`${p.width}×${p.height} · ${p.objects.length} objetos`;
 c.innerHTML='';for(const o of p.objects){const n=document.createElement('div');n.className='widget '+o.kind+(selected===o.id?' selected':'');n.dataset.id=o.id;Object.assign(n.style,{left:o.x+'px',top:o.y+'px',width:o.w+'px',height:o.h+'px'});let html='';if(o.kind==='lamp')html='<div class="inner"></div>';else if(o.kind==='bar')html='<div class="track"><div class="fill"></div></div>';else html='<div class="inner">'+C.esc(o.text||o.kind)+'</div>';n.innerHTML=html;n.onpointerdown=e=>{if(e.button!==0)return;selected=o.id;drag={id:o.id,x:e.clientX,y:e.clientY,ox:o.x,oy:o.y};n.setPointerCapture(e.pointerId);renderProps();document.querySelectorAll('.widget').forEach(z=>z.classList.toggle('selected',z.dataset.id===o.id));};n.onpointermove=e=>{if(!drag||drag.id!==o.id)return;o.x=Math.max(0,Math.min(p.width-o.w,drag.ox+e.clientX-drag.x));o.y=Math.max(0,Math.min(p.height-o.h,drag.oy+e.clientY-drag.y));n.style.left=o.x+'px';n.style.top=o.y+'px';};n.onpointerup=()=>{drag=null;renderProps();};c.append(n);}
 c.onclick=e=>{if(e.target===c){selected=null;renderProps();document.querySelectorAll('.widget').forEach(z=>z.classList.remove('selected'));}};}
function opts(value,filter=()=>true){return '<option value="">— variable —</option>'+p.variables.filter(v=>v.expose&&v.live&&filter(v)).map(v=>`<option value="${C.esc(v.name)}" ${v.name===value?'selected':''}>${C.esc(v.name)} · ${v.type} · ${v.access}</option>`).join('');}
function renderProps(){const host=$('#properties'),o=p.objects.find(o=>o.id===selected);if(!o){host.innerHTML='<p class="hint">Selecciona un elemento.</p>';return;}const numeric=v=>['SINT','USINT','INT','UINT','DINT','UDINT','LINT','ULINT','REAL','LREAL'].includes(v.type);const bindFilter=v=>o.kind==='lamp'?v.type==='BOOL':o.kind==='button'?v.type==='BOOL'&&v.writeSupported:o.kind==='input'?numeric(v)&&v.writeSupported:o.kind==='bar'?numeric(v):true;
 host.innerHTML=`<label>Tipo<input value='${o.kind}' disabled></label><label>Texto<input data-p='text' value='${C.esc(o.text)}'></label>${o.kind!=='text'?`<label>Variable<select data-p='binding'>${opts(o.binding,bindFilter)}</select></label>`:''}${o.kind==='button'?`<label>Acción BOOL<select data-p='actionMode'><option value='set' ${(o.actionMode||'set')==='set'?'selected':''}>SET · escribir TRUE</option><option value='reset' ${o.actionMode==='reset'?'selected':''}>RESET · escribir FALSE</option><option value='toggle' ${o.actionMode==='toggle'?'selected':''}>TOGGLE · invertir valor</option></select></label>`:''}${['value','input'].includes(o.kind)?`<label>Decimales<input data-p='decimals' type='number' min='0' max='6' step='1' value='${Number.isInteger(Number(o.decimals))?o.decimals:2}'></label>`:''}${o.kind==='bar'?`<div class='grid2'><label>Mín<input data-p='min' type='number' value='${o.min}'></label><label>Máx<input data-p='max' type='number' value='${o.max}'></label></div>`:''}<div class='grid2'><label>X<input data-p='x' type='number' value='${Math.round(o.x)}'></label><label>Y<input data-p='y' type='number' value='${Math.round(o.y)}'></label><label>Ancho<input data-p='w' type='number' value='${o.w}'></label><label>Alto<input data-p='h' type='number' value='${o.h}'></label></div><button id='deleteObj' class='delete'>Eliminar</button>`;
 host.querySelectorAll('[data-p]').forEach(x=>x.onchange=()=>{let v=x.value;if(['x','y','w','h','min','max','decimals'].includes(x.dataset.p))v=Number(v);o[x.dataset.p]=v;if(x.dataset.p==='binding'&&['button','input'].includes(o.kind)&&v){const tag=p.variables.find(t=>t.name===v);if(tag&&tag.writeSupported)tag.access='RW';renderVars();}renderCanvas();renderProps();renderDiag();});$('#deleteObj').onclick=()=>{p.objects=p.objects.filter(x=>x!==o);selected=null;render();};}
function renderDiag(){syncProjectInputs();const errors=C.validate(p),html=C.buildRuntimeHTML(p),chunks=Math.ceil(html.length/1400),exposed=p.variables.filter(v=>v.expose&&v.live);let list=[];list.push(`<div class="diagnostic ${errors.length?'error':'ok'}">${errors.length?'Bloqueos: '+errors.length:'Proyecto exportable'}</div>`);for(const e of errors.slice(0,5))list.push(`<div class="diagnostic error">${C.esc(e)}</div>`);list.push(`<div class="diagnostic">HTML estimado: ${(new TextEncoder().encode(html).length/1024).toFixed(1)} KB · ${chunks} fragmentos ST</div>`);list.push(`<div class="diagnostic">Tags POC: ${exposed.length}. Un cliente simultáneo, HTTP/1.0, polling ${p.pollMs} ms.</div>`);if(exposed.length>32)list.push('<div class="diagnostic warn">Para la primera prueba recomiendo ≤32 tags expuestos.</div>');if(html.length>500*1024)list.push('<div class="diagnostic warn">HTML >500 KB: mide memoria/tiempo de compilación antes de continuar.</div>');list.push('<div class="diagnostic ok">Servidor básico validado en NX102 real: HTML embebido y lectura de variables.</div>');$('#diagnostics').innerHTML=list.join('');}
function importText(text){try{const vars=C.importSysmac(text);p.variables=vars;p.objects.forEach(o=>{if(o.binding&&!vars.some(v=>v.name===o.binding))o.binding='';});render();toast(vars.length+' variables importadas');}catch(e){throw e;}}
function download(name,data,type='application/octet-stream'){const a=document.createElement('a'),blob=new Blob([data],{type});a.href=URL.createObjectURL(blob);a.download=name;document.body.append(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},500);}
function preview(){syncProjectInputs();const errors=C.validate(p);if(errors.length){toast('Corrige bloqueos antes de previsualizar');return;}const html=C.buildRuntimeHTML(p).replace('poll();</script>','document.getElementById("status").textContent="PREVIEW local · sin PLC";for(const v of P.vars){vals[v.name]=v.type==="BOOL"?false:55}paint();</script>');$('#previewFrame').srcdoc=html;$('#previewDialog').showModal();}
document.querySelectorAll('.tool-grid [data-kind]').forEach(b=>b.onclick=()=>{const o=C.newObject(b.dataset.kind);p.objects.push(o);selected=o.id;render();});
['projectName','port','pollMs','screenW','screenH'].forEach(id=>$('#'+id).onchange=()=>{syncProjectInputs();renderCanvas();renderDiag();});
$('#demoBtn').onclick=()=>{p=C.demoProject();selected=null;render()};$('#newBtn').onclick=()=>{p=C.newProject();selected=null;render()};
$('#importFileBtn').onclick=()=>$('#varsFile').click();$('#varsFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{importText(await f.text())}catch(err){toast(err.message)}e.target.value='';};
$('#pasteBtn').onclick=()=>{$('#pasteText').value='';$('#pasteError').textContent='';$('#pasteDialog').showModal()};$('#pasteImport').onclick=()=>{try{importText($('#pasteText').value);$('#pasteDialog').close()}catch(e){$('#pasteError').textContent=e.message}};
$('#previewBtn').onclick=preview;$('#closePreview').onclick=()=>$('#previewDialog').close();
$('#saveBtn').onclick=()=>{syncProjectInputs();download((p.name||'project').replace(/[^A-Za-z0-9_-]+/g,'_')+'.nxst',JSON.stringify(p,null,2),'application/json')};$('#loadBtn').onclick=()=>$('#projectFile').click();$('#projectFile').onchange=async e=>{try{const q=JSON.parse(await e.target.files[0].text());const errs=C.validate(q).filter(x=>!x.includes('selecciona una variable'));p=q;selected=null;render();if(errs.length)toast('Proyecto abierto con avisos')}catch(err){toast('Proyecto no válido: '+err.message)}e.target.value='';};
$('#exportBtn').onclick=()=>{syncProjectInputs();try{const out=C.exportPackage(p),name=(p.name||'WebHMI_ST').replace(/[^A-Za-z0-9_-]+/g,'_')+'_Sysmac.zip';download(name,out.zip,'application/zip');toast('Paquete Sysmac generado')}catch(e){toast(e.message)}};
render();
})();
