(function(root){'use strict';
const LIVE_TYPES=new Set(['BOOL','SINT','USINT','INT','UINT','DINT','UDINT','LINT','ULINT','REAL','LREAL','STRING']);
const WRITE_TYPES=new Set(['BOOL','SINT','USINT','INT','UINT','DINT','UDINT','LINT','ULINT','REAL','LREAL','STRING']);
const NUMERIC_TYPES=new Set(['SINT','USINT','INT','UINT','DINT','UDINT','LINT','ULINT','REAL','LREAL']);
const BOOL_WIDGETS=new Set(['status']);
const STATUS_SYMBOLS=new Set(['lamp','motor','pump','valve','conveyor','sensor']);
const LEGACY_STATUS_KINDS=new Set(['lamp','motor','pump','valve','conveyor','sensor']);
const IMAGE_MAX_BYTES=64*1024,IMAGE_TOTAL_MAX_BYTES=256*1024,HTML_MAX_BYTES=512*1024,IMAGE_OPTIMIZE_MAX_DIM=1024;
const enc=new TextEncoder();
function dataUrlBytes(data){const s=String(data||''),i=s.indexOf(',');if(i<0)return enc.encode(s).length;const meta=s.slice(0,i),body=s.slice(i+1);if(/;base64$/i.test(meta)){const clean=body.replace(/\s/g,'');const pad=clean.endsWith('==')?2:clean.endsWith('=')?1:0;return Math.max(0,Math.floor(clean.length*3/4)-pad);}try{return enc.encode(decodeURIComponent(body)).length}catch{return enc.encode(body).length;}}
const id=()=>Math.random().toString(36).slice(2,10);
const copy=x=>JSON.parse(JSON.stringify(x));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function typeInfo(raw){const s=String(raw||'').trim().toUpperCase().replace(/\s+/g,'');const m=s.match(/^STRING(?:\[(\d+)\]|\((\d+)\))?$/);if(m)return{type:'STRING',length:Number(m[1]||m[2]||255),raw:s};const a={BOOLEAN:'BOOL',INTEGER:'INT',SIGNEDINT:'INT',DOUBLEINTEGER:'DINT',UNSIGNEDINT:'UINT',DOUBLEUNSIGNEDINTEGER:'UDINT',FLOAT:'REAL',DOUBLEFLOAT:'LREAL'};return{type:a[s]||s,length:null,raw:s};}
function nameOK(n){return /^[A-Za-z_][A-Za-z0-9_]*(?:\.[A-Za-z_][A-Za-z0-9_]*)*$/.test(String(n||''));}
function parseDelimited(text){text=String(text||'').replace(/^\uFEFF/,'').trim();if(!text)return[];const first=text.split(/\r?\n/)[0],sep=first.includes('\t')?'\t':first.includes(';')?';':',';let rows=[],row=[],field='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){field+='"';i++;}else quoted=!quoted;}else if(c===sep&&!quoted){row.push(field.trim());field='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(field.trim());if(row.some(Boolean))rows.push(row);row=[];field='';}else field+=c;}row.push(field.trim());if(row.some(Boolean))rows.push(row);return rows;}
function parseST(text){const out=[];for(const line of String(text||'').split(/\r?\n/)){const clean=line.replace(/\(\*.*?\*\)/g,'').replace(/\/\/.*$/,'').trim();const m=clean.match(/^([A-Za-z_][A-Za-z0-9_]*(?:\.[A-Za-z_][A-Za-z0-9_]*)*)\s*:\s*([A-Za-z][A-Za-z0-9_]*(?:\s*[\[(]\s*\d+\s*[\])])?)/);if(m){const t=typeInfo(m[2]);out.push({name:m[1],type:t.type,stringLength:t.length,comment:'',sourceType:t.raw});}}return out;}
function importSysmac(text){const trimmed=String(text||'').trim();if(!trimmed)throw new Error('No hay contenido para importar.');let raw=[];if(/^\s*[A-Za-z_][A-Za-z0-9_.]*\s*:\s*[A-Za-z]/m.test(trimmed)&&!/^(?:Name|Nombre|Variable)[\t;,]/i.test(trimmed))raw=parseST(trimmed);const rows=parseDelimited(trimmed),norm=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[\s_.\-/]/g,'');if(!raw.length&&rows.length){const h=rows[0].map(norm),ni=h.findIndex(x=>['name','nombre','variablename','variable','symbol','simbolo'].includes(x)),ti=h.findIndex(x=>['datatype','type','tipo','tipodedatos','datatypeofvariable'].includes(x)),ci=h.findIndex(x=>['comment','comments','comentario','description','descripcion'].includes(x));if(ni>=0&&ti>=0){for(const row of rows.slice(1)){if(!row[ni])continue;const t=typeInfo(row[ti]);raw.push({name:row[ni],type:t.type,stringLength:t.length,comment:row[ci]||''});}}else if(rows[0].length>=2&&!trimmed.includes(':=')){for(const row of rows){const t=typeInfo(row[1]);raw.push({name:row[0],type:t.type,stringLength:t.length,comment:row[2]||''});}}}if(!raw.length)raw=parseST(trimmed);if(!raw.length)throw new Error('No se reconocen variables. Usa Name/Nombre + Data Type/Tipo, o declaraciones ST simples.');const seen=new Set(),errors=[],vars=[];for(const r of raw){if(!nameOK(r.name)){errors.push('Nombre no compatible: '+r.name);continue;}if(seen.has(r.name)){errors.push('Duplicada: '+r.name);continue;}seen.add(r.name);const live=LIVE_TYPES.has(r.type),stringLength=r.stringLength||255;vars.push({id:vars.length+1,name:r.name,type:r.type,stringLength,comment:r.comment||'',access:'R',expose:live,live,writeSupported:WRITE_TYPES.has(r.type)&&(r.type!=='STRING'||stringLength<=512)});}if(errors.length)throw new Error(errors.slice(0,12).join('\n'));return vars;}
function newScreen(name='Principal'){return{id:id(),name,objects:[]};}
function newProject(){return{name:'WebHMI ST',port:8080,pollMs:500,width:1024,height:600,minDisplayWidth:480,maxDisplayWidth:1920,variables:[],screens:[newScreen()],assets:[],alarms:[],recipes:[]};}
function normalize(input){const p=copy(input||newProject());p.minDisplayWidth=Number(p.minDisplayWidth??480);p.maxDisplayWidth=Number(p.maxDisplayWidth??1920);p.variables=Array.isArray(p.variables)?p.variables:[];for(const v of p.variables){const t=typeInfo(v.type);v.type=t.type;v.stringLength=Number(v.stringLength||t.length||255);v.live=LIVE_TYPES.has(v.type);v.writeSupported=WRITE_TYPES.has(v.type)&&(v.type!=='STRING'||v.stringLength<=512);if(v.access!=='R'&&v.access!=='RW')v.access='R';if(typeof v.expose!=='boolean')v.expose=v.live;}p.assets=Array.isArray(p.assets)?p.assets:[];p.alarms=Array.isArray(p.alarms)?p.alarms:[];p.recipes=Array.isArray(p.recipes)?p.recipes:[];if(!Array.isArray(p.screens)||!p.screens.length){p.screens=[{id:id(),name:'Principal',objects:Array.isArray(p.objects)?p.objects:[]}];delete p.objects;}for(const s of p.screens){s.id=s.id||id();s.name=s.name||'Pantalla';s.objects=Array.isArray(s.objects)?s.objects:[];for(const o of s.objects){if(LEGACY_STATUS_KINDS.has(o.kind)){o.symbolType=o.kind;o.kind='status';}o.symbolType=STATUS_SYMBOLS.has(o.symbolType)?o.symbolType:'lamp';o.actionType=o.actionType||'write';o.targetScreenId=o.targetScreenId||'';o.actionMode=o.actionMode||'set';o.feedbackBinding=o.feedbackBinding||'';o.feedbackColorOff=/^#[0-9a-f]{6}$/i.test(o.feedbackColorOff||'')?o.feedbackColorOff:'#2563eb';o.feedbackColorOn=/^#[0-9a-f]{6}$/i.test(o.feedbackColorOn||'')?o.feedbackColorOn:'#16a34a';o.decimals=Number.isInteger(Number(o.decimals))?Number(o.decimals):2;o.min=Number.isFinite(Number(o.min))?Number(o.min):0;o.max=Number.isFinite(Number(o.max))?Number(o.max):100;}}return p;}
function newObject(kind){const base={id:id(),kind,x:40,y:40,w:150,h:50,text:'',binding:'',assetId:'',symbolType:'lamp',actionType:'write',targetScreenId:'',actionMode:'set',feedbackBinding:'',feedbackColorOff:'#2563eb',feedbackColorOn:'#16a34a',decimals:2,min:0,max:100};const m={text:{w:220,h:40,text:'Texto'},status:{w:110,h:100,text:'Estado'},value:{w:160,h:50,text:'Valor'},input:{w:210,h:55,text:'Entrada'},button:{w:170,h:58,text:'Botón'},bar:{w:240,h:36,text:'Barra'},image:{w:240,h:160,text:'Imagen'},tank:{w:140,h:190,text:'Depósito'}};return Object.assign(base,m[kind]||{});}
function demoProject(){const p=newProject();p.name='Demo NX ST';p.variables=[{id:1,name:'Machine_Running',type:'BOOL',stringLength:255,comment:'Máquina en marcha',access:'RW',expose:true,live:true,writeSupported:true},{id:2,name:'Process_Setpoint',type:'REAL',stringLength:255,comment:'Consigna',access:'RW',expose:true,live:true,writeSupported:true},{id:3,name:'Process_Level',type:'REAL',stringLength:255,comment:'Nivel',access:'R',expose:true,live:true,writeSupported:true},{id:4,name:'Start_Request',type:'BOOL',stringLength:255,comment:'Solicitud marcha',access:'RW',expose:true,live:true,writeSupported:true}];const s=p.screens[0];s.objects=[Object.assign(newObject('text'),{x:30,y:24,text:'HMI NX · servidor ST embebido'}),Object.assign(newObject('status'),{x:40,y:100,binding:'Machine_Running',symbolType:'motor',text:'Motor'}),Object.assign(newObject('value'),{x:200,y:105,text:'Nivel',binding:'Process_Level'}),Object.assign(newObject('tank'),{x:430,y:90,binding:'Process_Level'}),Object.assign(newObject('input'),{x:200,y:190,text:'Consigna',binding:'Process_Setpoint'}),Object.assign(newObject('button'),{x:40,y:270,text:'Marcha SET',binding:'Start_Request',actionMode:'set'})];p.alarms=[{id:id(),name:'Nivel alto',binding:'Process_Level',operator:'gt',value:90,severity:'high'}];p.recipes=[{id:id(),name:'Producción 50',values:{Process_Setpoint:50}}];return p;}
function variableMap(p){return new Map(p.variables.map(v=>[v.name,v]));}
function typedFor(v,value){if(v.type==='BOOL'){if(value===true||value===false)return value;if(String(value).toLowerCase()==='true'||String(value)==='1')return true;if(String(value).toLowerCase()==='false'||String(value)==='0')return false;throw new Error('BOOL inválido');}if(NUMERIC_TYPES.has(v.type)){const n=Number(value);if(!Number.isFinite(n))throw new Error('Número inválido');return n;}return String(value);}
function validate(input){const p=normalize(input),e=[];if(!Number.isInteger(+p.port)||p.port<1024||p.port>65535)e.push('Puerto: use 1024..65535.');if(!Number.isInteger(+p.pollMs)||p.pollMs<100||p.pollMs>5000)e.push('Polling: 100..5000 ms.');if(!Number.isInteger(+p.width)||p.width<320||p.width>3840)e.push('Ancho de diseño: 320..3840 px.');if(!Number.isInteger(+p.height)||p.height<240||p.height>2160)e.push('Alto de diseño: 240..2160 px.');if(p.minDisplayWidth>p.maxDisplayWidth)e.push('El ancho mínimo no puede superar al máximo.');if(p.screens.length>20)e.push('Máximo 20 pantallas en esta versión.');const exposed=p.variables.filter(v=>v.expose&&v.live);if(exposed.length>32)e.push('máximo 32 variables expuestas en esta versión.');const vm=variableMap(p),assetIds=new Set(p.assets.map(a=>a.id)),screenIds=new Set(p.screens.map(s=>s.id));let assetTotal=0;for(const a of p.assets){const bytes=dataUrlBytes(a.data);assetTotal+=bytes;if(!/^data:image\/(png|jpeg|webp|svg\+xml);base64,/i.test(String(a.data||'')))e.push('Imagen '+(a.name||a.id)+': formato embebido no válido.');if(bytes>IMAGE_MAX_BYTES)e.push('Imagen '+(a.name||a.id)+': supera el límite estricto de 64 KB.');}if(assetTotal>IMAGE_TOTAL_MAX_BYTES)e.push('Imágenes del proyecto: superan el límite total estricto de 256 KB.');for(const v of p.variables){if(v.access==='RW'&&!v.writeSupported)e.push(v.name+': escritura no soportada para '+v.type+(v.type==='STRING'?' (máximo 512 bytes en esta versión)':'')+'.');}
 for(const s of p.screens){if(!s.name)e.push('Pantalla sin nombre.');for(const o of s.objects){if(o.kind==='text')continue;if(o.kind==='image'){if(!assetIds.has(o.assetId))e.push(s.name+': selecciona imagen para '+o.text);continue;}if(o.kind==='button'&&o.actionType==='navigate'){if(!screenIds.has(o.targetScreenId))e.push(o.text+': selecciona pantalla destino.');if(o.feedbackBinding){const fb=vm.get(o.feedbackBinding);if(!fb)e.push(o.text+': variable de feedback no válida.');else{if(fb.type!=='BOOL')e.push(o.text+': feedback requiere BOOL.');if(!fb.expose)e.push(o.text+': variable de feedback debe estar expuesta.');}if(!/^#[0-9a-f]{6}$/i.test(o.feedbackColorOff||'')||!/^#[0-9a-f]{6}$/i.test(o.feedbackColorOn||''))e.push(o.text+': colores de feedback no válidos.');}continue;}const v=vm.get(o.binding);if(!v)e.push(s.name+' / '+o.text+': selecciona variable.');else{if(['button','input'].includes(o.kind)&&v.access!=='RW')e.push(o.text+': requiere variable RW.');if((BOOL_WIDGETS.has(o.kind)||o.kind==='button')&&v.type!=='BOOL')e.push(o.text+': requiere BOOL.');if(['bar','tank'].includes(o.kind)&&!NUMERIC_TYPES.has(v.type))e.push(o.text+': requiere tipo numérico.');if(o.kind==='input'&&!(NUMERIC_TYPES.has(v.type)||v.type==='STRING'))e.push(o.text+': requiere tipo numérico o STRING.');}if(o.kind==='status'&&!STATUS_SYMBOLS.has(o.symbolType))e.push(o.text+': símbolo de estado no válido.');if(o.kind==='button'){if(!['set','reset','toggle'].includes(o.actionMode))e.push(o.text+': modo SET/RESET/TOGGLE no válido.');if(o.feedbackBinding){const fb=vm.get(o.feedbackBinding);if(!fb)e.push(o.text+': variable de feedback no válida.');else{if(fb.type!=='BOOL')e.push(o.text+': feedback requiere BOOL.');if(!fb.expose)e.push(o.text+': variable de feedback debe estar expuesta.');}if(!/^#[0-9a-f]{6}$/i.test(o.feedbackColorOff||'')||!/^#[0-9a-f]{6}$/i.test(o.feedbackColorOn||''))e.push(o.text+': colores de feedback no válidos.');}}if(['value','input'].includes(o.kind)&&(o.decimals<0||o.decimals>6))e.push(o.text+': decimales 0..6.');}}
 const alarmIds=new Set();for(const a of p.alarms){if(alarmIds.has(a.id))e.push('ID de alarma duplicado.');alarmIds.add(a.id);const v=vm.get(a.binding);if(!v)e.push('Alarma '+a.name+': variable no válida.');if(!['eq','ne','gt','ge','lt','le'].includes(a.operator))e.push('Alarma '+a.name+': operador no válido.');if(v&&v.type==='STRING'&&!['eq','ne'].includes(a.operator))e.push('Alarma '+a.name+': STRING sólo admite = o ≠.');if(v)try{typedFor(v,a.value)}catch{e.push('Alarma '+a.name+': umbral no válido.');}}
 for(const r of p.recipes){if(!r.name)e.push('Receta sin nombre.');for(const [name,val] of Object.entries(r.values||{})){const v=vm.get(name);if(!v||v.access!=='RW'||!v.writeSupported)e.push('Receta '+r.name+': '+name+' debe ser RW compatible.');else try{typedFor(v,val)}catch{e.push('Receta '+r.name+': valor inválido en '+name);}}}
 return [...new Set(e)];}
root.NXST=Object.assign(root.NXST||{},{LIVE_TYPES,WRITE_TYPES,NUMERIC_TYPES,BOOL_WIDGETS,STATUS_SYMBOLS,LEGACY_STATUS_KINDS,IMAGE_MAX_BYTES,IMAGE_TOTAL_MAX_BYTES,HTML_MAX_BYTES,IMAGE_OPTIMIZE_MAX_DIM,dataUrlBytes,id,copy,esc,typeInfo,nameOK,parseDelimited,importSysmac,newProject,newScreen,newObject,demoProject,normalize,typedFor,validate});
})(globalThis);
