#!/usr/bin/env node
/* Offline user provisioning for the reference bench. Not an NX account installer. */
'use strict';const fs=require('node:fs'),path=require('node:path');const {hashPassword,atomicFile}=require('./reference.cjs');
async function provision({directory,id,name,role,password}){if(!/^[A-Za-z0-9_.-]{1,64}$/.test(id))throw new Error('ID no válido');const file=path.join(path.resolve(directory),'users.json'),users=fs.existsSync(file)?JSON.parse(fs.readFileSync(file,'utf8')):[];if(users.some(u=>u.id===id))throw new Error('El usuario ya existe');users.push({id,name,role,disabled:false,...await hashPassword(password)});atomicFile(file,users);return {id,name,role};}
module.exports={provision};
if(require.main===module){const args=process.argv.slice(2),arg=k=>args[args.indexOf(k)+1];const directory=arg('--private'),id=arg('--user'),role=arg('--role'),name=args.includes('--name')?arg('--name'):id;if(!args.includes('--private')||!args.includes('--user')||!args.includes('--role')){console.error('Uso: node provision.cjs --private /ruta/privada --user id --role admin [--name nombre]. Contraseña por stdin, nunca por argumento.');process.exit(1);}let password='';
 if(process.stdin.isTTY){process.stdout.write('Contraseña (12–256 caracteres, no se muestra): ');process.stdin.setRawMode(true);process.stdin.resume();process.stdin.setEncoding('utf8');process.stdin.on('data',chunk=>{for(const ch of chunk){if(ch==='\u0003')process.exit(1);if(ch==='\r'||ch==='\n'){process.stdin.setRawMode(false);process.stdin.pause();process.stdout.write('\n');run();return;}if(ch==='\u007f')password=password.slice(0,-1);else if(ch>=' ')password+=ch;}});}else{process.stdin.setEncoding('utf8');process.stdin.on('data',c=>{password+=c;if(password.length>1024)process.exit(1);});process.stdin.on('end',()=>{password=password.replace(/[\r\n]+$/,'');run();});}
 async function run(){try{const user=await provision({directory,id,role,name,password});password='';console.log('Provisionado usuario de banco:',user.id);}catch(e){console.error(e.message);process.exitCode=1;}}
}
