/* HMI NX Designer 0.2. No editor accounts or edit authorization. Roles belong to operation. */
(function(){
'use strict';const C=NXCore,R=NXRuntime,$=s=>document.querySelector(s),esc=C.esc,el=NXWidgets.el;
const S={p:C.demoProject(),screen:null,selected:null,selection:[],tab:'editor',zoom:.75,grid:true,history:[],future:[],recipe:null,runtime:null,clipboard:[]};S.screen=S.p.screens[0].id;
let saveTimer,toastTimer,dbPromise;
function toast(message){$('#toast').textContent=message;$('#toast').style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').style.display='none',6000);}
function db(){return dbPromise||(dbPromise=new Promise((resolve,reject)=>{const r=indexedDB.open('HMI_NX_Designer',1);r.onupgradeneeded=()=>r.result.createObjectStore('projects',{keyPath:'id'});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);}));}
async function store(mode,work){const database=await db();return new Promise((resolve,reject)=>{const tx=database.transaction('projects',mode);let request;try{request=work(tx.objectStore('projects'));}catch(e){reject(e);return;}tx.oncomplete=()=>resolve(request?.result);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||new Error('Guardado cancelado'));});}
async function saveNow(){clearTimeout(saveTimer);const snapshot=C.copy(S.p);try{await store('readwrite',s=>s.put({id:snapshot.id,name:snapshot.name,updated:Date.now(),project:snapshot}));localStorage.setItem('HMI_NX_active',snapshot.id);$('#save-state').textContent='✓ Guardado local';}catch(e){$('#save-state').textContent='Sin guardar · descargue .nxhmi';toast('Guardado del navegador no disponible: '+e.message);}}
function autosave(){$('#save-state').textContent='Guardando…';clearTimeout(saveTimer);saveTimer=setTimeout(saveNow,600);}
function checkpoint(){S.history.push(JSON.stringify(S.p));if(S.history.length>40)S.history.shift();S.future=[];}
function mutate(fn,redraw=true){checkpoint();fn();S.p.revision++;autosave();if(redraw)render();}
function current(){return C.findView(S.p,S.screen)||S.p.screens[0];}
function selected(){return current().objects.find(o=>o.id===S.selected);}
function selectedObjects(){return current().objects.filter(o=>S.selection.includes(o.id));}
function select(ids){S.selection=[...new Set(ids)].filter(id=>current().objects.some(o=>o.id===id));S.selected=S.selection.at(-1)||null;}
const download=NXData.download;
function modal(title,html='',preview=false){closeModal();$('#modal-title').textContent=title;$('#modal-body').innerHTML=html;$('#modal').className=preview?'preview-dialog':'';$('#modal').showModal();}
function closeModal(){if(S.runtime){S.runtime.stop();S.runtime=null;}$('#modal').close();}
function options(values,value){return values.map(v=>{const[id,label]=Array.isArray(v)?v:[v,v];return `<option value="${esc(id)}" ${String(id)===String(value)?'selected':''}>${esc(label)}</option>`;}).join('');}
function field(label,key,value,type='text',wide=false){return `<label class="${wide?'wide':''}">${esc(label)}<input data-prop="${key}" type="${type}" value="${esc(value)}" ${type==='number'?'step="any"':''}></label>`;}
function choose(label,key,value,values,wide=true){return `<label class="${wide?'wide':''}">${esc(label)}<select data-prop="${key}">${options(values,value)}</select></label>`;}
function check(label,key,value){return `<label class="check-line wide"><input data-prop="${key}" type="checkbox" ${value?'checked':''}>${esc(label)}</label>`;}
const labels={text:['T','Texto'],rectangle:['□','Rectángulo'],circle:['○','Círculo'],line:['─','Línea'],button:['▭','Botón'],lamp:['●','Lámpara'],value:['123','Valor'],input:['⌨','Entrada'],bar:['▰','Barra'],level:['▥','Nivel'],image:['▧','Imagen'],alarms:['⚠','Alarmas'],recipes:['☷','Recetas'],switch:['◉','ON / OFF'],selector:['≡','Selector'],slider:['↔','Slider'],symbol:['⚙','Símbolo'],banner:['!','Banner'],audit:['≣','Operaciones'],clock:['◷','Reloj'],user:['♙','Usuario'],navigation:['⇢','Menú']};
function availableVariables(){const s=current();return [...S.p.variables,...s.slots.map(v=>({...v,name:'$'+v.name,access:'RW',initial:v.type==='BOOL'?false:v.type==='STRING'?'':0}))];}
function addObject(kind,x=40,y=40,assetId=''){
 if(!C.KINDS.includes(kind))return;mutate(()=>{const s=current(),o=C.newObject(kind,x,y),vars=availableVariables();o.w=Math.min(o.w,s.width);o.h=Math.min(o.h,s.height);o.x=Math.max(0,Math.min(x,s.width-o.w));o.y=Math.max(0,Math.min(y,s.height-o.h));
 const v=vars.find(v=>['lamp','switch','symbol'].includes(kind)?v.type==='BOOL':['bar','level','slider','selector'].includes(kind)?['REAL','DINT'].includes(v.type)&&(!['slider','selector'].includes(kind)||v.access==='RW'):['input','button'].includes(kind)?v.access==='RW':true);
 if(v&&['lamp','bar','level','input','button','value','symbol','switch','selector','slider'].includes(kind)){o.binding=v.name;o.writeBinding=['input','button','switch','selector','slider'].includes(kind)?v.name:'';if(kind==='button')o.writeValue=String(v.type==='BOOL'?true:v.initial);}
 o.assetId=assetId;for(const key of ['readRoles','operateRoles','recipeEditRoles'])o[key]=o[key].filter(id=>id==='*'||S.p.security.roles.some(r=>r.id===id));s.objects.push(o);select([o.id]);});
}
function roleFields(o,key,label){return `<fieldset class="permission-field"><legend>${label}</legend>${[['*','Todos'],...S.p.security.roles.map(r=>[r.id,r.name])].map(([id,name])=>`<label><input type="checkbox" data-object-role="${key}" value="${esc(id)}" ${(o[key]||[]).includes(id)?'checked':''}>${esc(name)}</label>`).join('')}</fieldset>`;}
function inspector(){
 const host=$('#inspector');if(!host)return;const s=current(),o=selected();
 if(!o){host.innerHTML=`<div class="panel-section"><div class="section-title">${s.kind==='screen'?'Pantalla':s.kind==='master'?'Página maestra':'Pop-up / Faceplate'}</div><h3>${esc(s.name)}</h3><label class="field">Fondo<input id="view-bg" type="color" value="${s.background}"></label><div class="property-grid"><label>Ancho<input id="view-width" type="number" value="${s.width}"></label><label>Alto<input id="view-height" type="number" value="${s.height}"></label></div>${s.kind==='screen'?`<label class="field">Página maestra<select id="view-master">${options([['','Sin maestra'],...S.p.masters.map(m=>[m.id,m.name])],s.masterId)}</select></label>`:''}<p class="hint">Selecciona un objeto. Ctrl/Cmd o Shift permiten selección múltiple. Los elementos de la maestra se editan en su propia vista.</p>${s.kind==='popup'?`<h4>Parámetros del faceplate</h4><div id="popup-slots">${s.slots.map((v,i)=>`<div class="slot-row"><code>$${esc(v.name)}</code><span>${v.type}</span><button data-delete-slot="${i}">✕</button></div>`).join('')}</div><button id="add-slot">＋ Parámetro</button>`:''}</div>`;
 $('#view-bg').onchange=e=>mutate(()=>s.background=e.target.value);$('#view-master')?.addEventListener('change',e=>mutate(()=>s.masterId=e.target.value));
 for(const key of ['width','height'])$('#view-'+key).onchange=e=>{const n=Number(e.target.value);if(!Number.isInteger(n)||n<100||n>3840||s.objects.some(o=>key==='width'?o.x+o.w>n:o.y+o.h>n)){toast('Dimensión no válida o deja objetos fuera.');inspector();return;}mutate(()=>s[key]=n);};
 $('#add-slot')?.addEventListener('click',()=>{modal('Parámetro de faceplate',`<label class="field">Nombre sin $<input id="slot-name" value="run"></label><label class="field">Tipo<select id="slot-type">${options(C.TYPES,'BOOL')}</select></label><button id="save-slot" class="primary">Añadir</button>`);$('#save-slot').onclick=()=>{const name=$('#slot-name').value.trim(),type=$('#slot-type').value;if(!C.nameOK(name)||s.slots.some(x=>x.name===name)){toast('Nombre inválido o repetido');return;}mutate(()=>s.slots.push({name,type}));closeModal();};});
 host.querySelectorAll('[data-delete-slot]').forEach(b=>b.onclick=()=>{const slot=s.slots[Number(b.dataset.deleteSlot)];if(s.objects.some(o=>JSON.stringify(o).includes('"$'+slot.name+'"'))){toast('El parámetro está utilizado. Retira primero sus enlaces.');return;}mutate(()=>s.slots.splice(Number(b.dataset.deleteSlot),1));});return;
 }
 const vars=availableVariables(),tagList=[['','— Sin variable —'],...vars.map(v=>[v.name,`${v.name} · ${v.type} · ${v.access}`])],bools=[['','Ninguna'],...vars.filter(v=>v.type==='BOOL').map(v=>v.name)];
 let html=field('Etiqueta','text',o.text,'text',true)+field('X','x',o.x,'number')+field('Y','y',o.y,'number')+field('Ancho','w',o.w,'number')+field('Alto','h',o.h,'number')+field('Texto px','fontSize',o.fontSize,'number')+field('Color texto','color',o.color,'color')+field('Fondo','background',o.background,'color')+check('Bloquear posición','locked',o.locked);
 if(!['rectangle','circle','line','alarms','banner','recipes','audit','clock','user','navigation'].includes(o.kind))html+=choose('Variable de lectura / animación','binding',o.binding,tagList);
 if(['button','input','switch','selector','slider'].includes(o.kind))html+=choose('Variable de escritura','writeBinding',o.writeBinding,tagList.filter(([id])=>!id||vars.find(v=>v.name===id)?.access==='RW'));
 if(['lamp','symbol'].includes(o.kind))html+=field('Color ON','onColor',o.onColor,'color')+field('Color OFF','offColor',o.offColor,'color');
 if(o.kind==='symbol')html+=choose('Símbolo','symbol',o.symbol,C.SYMBOLS);
 if(['bar','level','slider','value','input'].includes(o.kind))html+=field('Unidad','unit',o.unit)+field('Decimales','digits',o.digits,'number');
 if(['bar','level','slider'].includes(o.kind))html+=field('Mínimo','min',o.min,'number')+field('Máximo','max',o.max,'number')+choose('Orientación','orientation',o.orientation,[['horizontal','Horizontal'],['vertical','Vertical']]);
 if(o.kind==='slider')html+=field('Paso','step',o.step,'number')+choose('Enviar valor','writeMode',o.writeMode,[['release','Al soltar'],['apply','Botón Aplicar'],['continuous','Durante arrastre (máx. 4/s)']]);
 if(o.kind==='input')html+=check('Teclado virtual','keyboard',o.keyboard);
 if(o.kind==='selector')html+=`<label class="wide">Posiciones: valor = texto, una por línea<textarea data-options rows="4">${esc(o.options.map(v=>v.value+' = '+v.label).join('\n'))}</textarea></label>`;
 if(o.kind==='button'){
 html+=choose('Acción','action',o.action,[['write','Escribir valor'],['pulse','Solicitar pulso PLC'],['navigate','Cambiar pantalla'],['popup','Abrir pop-up / faceplate'],['closePopup','Cerrar pop-up'],['login','Identificar operador'],['logout','Cerrar sesión']]);
 if(o.action==='write')html+=field('Valor solicitado','writeValue',o.writeValue,'text',true);
 if(o.action==='navigate')html+=choose('Pantalla destino','targetScreen',o.targetScreen,[['','— Seleccionar —'],...S.p.screens.map(v=>[v.id,v.name])]);
 if(o.action==='popup'){html+=choose('Ventana destino','targetScreen',o.targetScreen,[['','— Seleccionar —'],...S.p.popups.map(v=>[v.id,v.name])]);const pop=S.p.popups.find(v=>v.id===o.targetScreen);for(const slot of pop?.slots||[])html+=`<label class="wide">$${esc(slot.name)} (${slot.type})<select data-slot-binding="${esc(slot.name)}">${options([['','— Asignar variable —'],...S.p.variables.filter(v=>v.type===slot.type).map(v=>v.name)],o.popupBindings[slot.name])}</select></label>`;}
 }
 if(o.kind==='image')html+=choose('Imagen','assetId',o.assetId,[['','— Seleccionar —'],...S.p.assets.map(a=>[a.id,a.name])]);
 if(o.kind==='recipes')html+=`<fieldset class="permission-field wide"><legend>Parámetros permitidos en recetas (vacío: los de recetas iniciales)</legend>${S.p.variables.filter(v=>v.access==='RW').map(v=>`<label><input data-recipe-param type="checkbox" value="${esc(v.name)}" ${o.recipeVariables.includes(v.name)?'checked':''}>${esc(v.name)}</label>`).join('')}</fieldset>`;
 html+=choose('Mostrar cuando BOOL = TRUE','visibleBinding',o.visibleBinding,bools)+choose('Operar cuando BOOL = TRUE','enabledBinding',o.enabledBinding,bools)+choose('Sin permiso','deniedMode',o.deniedMode,[['disable','Deshabilitar'],['hide','Ocultar']])+check('Confirmar antes de operar','confirm',o.confirm);
 if(o.confirm)html+=field('Confirmación','confirmText',o.confirmText,'text',true);
 html+=choose('Animación básica','animation',o.animation,[['none','Ninguna'],['blink','Parpadeo'],['rotate','Giro']]);
 const rules=o.rules.map((r,i)=>`<div class="rule-box"><div class="row-actions"><strong>Regla ${i+1}</strong><button data-remove-rule="${i}">✕</button></div><label>Propiedad<select data-rule="${i}:property">${options([['color','Color'],['text','Texto'],['visible','Visibilidad'],['x','Desplazamiento X'],['y','Desplazamiento Y'],['rotate','Ángulo'],['width','Ancho'],['height','Alto'],['flow','Flujo']],r.property)}</select></label><label>Variable<select data-rule="${i}:variable">${options(tagList,r.variable)}</select></label><label>Comparación<select data-rule="${i}:operator">${options([['eq','='],['ne','≠'],['gt','>'],['ge','≥'],['lt','<'],['le','≤'],['range','Escalar rango']],r.operator)}</select></label>${r.operator==='range'?['from','to','outMin','outMax'].map((key,j)=>`<label>${['Entrada desde','Entrada hasta','Salida desde','Salida hasta'][j]}<input data-rule="${i}:${key}" type="number" step="any" value="${r[key]}"></label>`).join(''):`<label>Comparar con<input data-rule="${i}:value" value="${esc(r.value)}"></label><label>Resultado<input data-rule="${i}:output" type="${r.property==='color'?'color':'text'}" value="${esc(r.output)}"></label>`}</div>`).join('');
 host.innerHTML=`<div class="panel-section"><div class="section-title">${esc(labels[o.kind][1])}<span>${S.selection.length} seleccionados</span></div><div class="property-grid">${html}</div><details open><summary>Permisos de operación</summary>${roleFields(o,'readRoles','Puede visualizar')}${roleFields(o,'operateRoles','Puede operar')}${o.kind==='recipes'?roleFields(o,'recipeEditRoles','Puede editar recetas'):''}<p class="hint">La autorización real se impone en el servicio NX. No son permisos del editor.</p></details><details><summary>Reglas visuales (${o.rules.length})</summary>${rules}<button id="add-rule">＋ Regla</button></details></div>`;
 host.querySelectorAll('[data-prop]').forEach(input=>input.onchange=()=>{let value=input.type==='checkbox'?input.checked:input.type==='number'?Number(input.value):input.value;if(input.type==='number'&&!Number.isFinite(value))return;mutate(()=>{o[input.dataset.prop]=value;o.w=Math.max(20,Math.min(s.width,o.w));o.h=Math.max(20,Math.min(s.height,o.h));o.x=Math.max(0,Math.min(s.width-o.w,o.x));o.y=Math.max(0,Math.min(s.height-o.h,o.y));o.fontSize=Math.max(8,Math.min(120,o.fontSize));o.digits=Math.max(0,Math.min(6,o.digits));});});
 host.querySelectorAll('[data-object-role]').forEach(input=>input.onchange=()=>mutate(()=>{const key=input.dataset.objectRole;if(input.checked)o[key]=[...new Set([...o[key],input.value])];else o[key]=o[key].filter(x=>x!==input.value);}));
 host.querySelectorAll('[data-recipe-param]').forEach(input=>input.onchange=()=>mutate(()=>{o.recipeVariables=input.checked?[...new Set([...o.recipeVariables,input.value])]:o.recipeVariables.filter(n=>n!==input.value);}));
 host.querySelectorAll('[data-slot-binding]').forEach(input=>input.onchange=()=>mutate(()=>o.popupBindings[input.dataset.slotBinding]=input.value));
 host.querySelector('[data-options]')?.addEventListener('change',e=>{try{const values=e.target.value.split('\n').filter(x=>x.trim()).map(line=>{const i=line.indexOf('=');if(i<1)throw new Error('Use valor = texto');return {value:line.slice(0,i).trim(),label:line.slice(i+1).trim()};});mutate(()=>o.options=values);}catch(error){toast(error.message);}});
 $('#add-rule').onclick=()=>mutate(()=>o.rules.push({property:'color',variable:o.binding||vars[0]?.name||'',operator:'eq',value:'true',output:'#faad55',from:0,to:100,outMin:0,outMax:100}));
 host.querySelectorAll('[data-remove-rule]').forEach(b=>b.onclick=()=>mutate(()=>o.rules.splice(Number(b.dataset.removeRule),1)));
 host.querySelectorAll('[data-rule]').forEach(input=>input.onchange=()=>{const[i,key]=input.dataset.rule.split(':');mutate(()=>{o.rules[Number(i)][key]=input.type==='number'?Number(input.value):input.value;if(key==='property'&&input.value==='color')o.rules[Number(i)].output='#faad55';});});
}
function drawStage(){const stage=$('#stage');if(!stage)return;const s=current(),values=R.initial(S.p);Object.assign(stage.style,{width:s.width+'px',height:s.height+'px',backgroundColor:s.background,transform:`scale(${S.zoom})`});stage.classList.toggle('grid',S.grid);$('#canvas-wrap').style.width=s.width*S.zoom+'px';$('#canvas-wrap').style.height=s.height*S.zoom+'px';stage.replaceChildren();
 const master=S.p.masters.find(m=>m.id===s.masterId);for(const o of master?.objects||[]){const n=R.widget(o,S.p);R.refreshWidget(n,o,S.p,values,true,true);n.classList.add('from-master');stage.append(n);}
 for(const o of s.objects){const n=R.widget(o,S.p);R.refreshWidget(n,o,S.p,values,true,true);if(S.selection.includes(o.id)){n.classList.add('selected');if(!o.locked&&S.selection.length===1)n.append(el('span','resize-handle'));}if(o.locked)n.classList.add('position-locked');n.onpointerdown=e=>startDrag(e,o,n);stage.append(n);}
 if(!s.objects.length){const hint=el('div','empty-canvas');hint.append(el('strong','','Diseña '+s.name),el('span','','Arrastra un objeto desde la biblioteca'));stage.append(hint);}
 stage.onpointerdown=e=>{if(e.target===stage){select([]);drawStage();inspector();}};stage.ondragover=e=>{e.preventDefault();e.dataTransfer.dropEffect='copy';};stage.ondrop=async e=>{e.preventDefault();const rect=stage.getBoundingClientRect(),x=(e.clientX-rect.left)/S.zoom,y=(e.clientY-rect.top)/S.zoom;if(e.dataTransfer.files.length){await importImages(e.dataTransfer.files,x,y);return;}try{const data=JSON.parse(e.dataTransfer.getData('application/x-hmi-nx'));addObject(data.kind,x,y,data.assetId||'');}catch{toast('Arrastra un objeto de la biblioteca o una imagen.');}};
}
function startDrag(e,o,n){if(e.button!==0)return;e.preventDefault();e.stopPropagation();const resizing=e.target.classList.contains('resize-handle');if(e.shiftKey||e.ctrlKey||e.metaKey){select(S.selection.includes(o.id)?S.selection.filter(id=>id!==o.id):[...S.selection,o.id]);drawStage();inspector();return;}
 if(!S.selection.includes(o.id))select(o.groupId?current().objects.filter(a=>a.groupId===o.groupId).map(a=>a.id):[o.id]);S.selected=o.id;inspector();if(o.locked){drawStage();return;}
 const objects=selectedObjects().filter(o=>!o.locked),start=objects.map(o=>({o,x:o.x,y:o.y,w:o.w,h:o.h})),cx=e.clientX,cy=e.clientY,s=current();let moved=false;
 $('#stage').querySelectorAll('.nx-object').forEach(x=>x.classList.toggle('selected',S.selection.includes(x.dataset.id)));
 const move=ev=>{let dx=(ev.clientX-cx)/S.zoom,dy=(ev.clientY-cy)/S.zoom;if(!moved&&Math.abs(dx)+Math.abs(dy)<2)return;if(!moved){checkpoint();moved=true;}const snap=v=>S.grid?Math.round(v/10)*10:Math.round(v);dx=snap(dx);dy=snap(dy);
 if(resizing&&start.length===1){o.w=Math.max(20,Math.min(s.width-o.x,snap(start[0].w+dx)));o.h=Math.max(20,Math.min(s.height-o.y,snap(start[0].h+dy)));}
 else {dx=Math.max(-Math.min(...start.map(a=>a.x)),Math.min(s.width-Math.max(...start.map(a=>a.x+a.w)),dx));dy=Math.max(-Math.min(...start.map(a=>a.y)),Math.min(s.height-Math.max(...start.map(a=>a.y+a.h)),dy));for(const a of start){a.o.x=a.x+dx;a.o.y=a.y+dy;}}
 for(const a of start){const node=[...$('#stage').children].find(x=>x.dataset.id===a.o.id);if(node)Object.assign(node.style,{left:a.o.x+'px',top:a.o.y+'px',width:a.o.w+'px',height:a.o.h+'px'});}};
 const up=()=>{document.removeEventListener('pointermove',move);document.removeEventListener('pointerup',up);document.removeEventListener('pointercancel',up);if(moved){S.p.revision++;autosave();}drawStage();inspector();};document.addEventListener('pointermove',move);document.addEventListener('pointerup',up);document.addEventListener('pointercancel',up);
}
function designer(){const p=S.p,s=current(),list=(views,icon)=>views.map(a=>`<div class="screen-item"><button data-view="${a.id}" class="${a.id===s.id?'active':''}">${icon} ${esc(a.name)}</button><button class="mini" data-rename-view="${a.id}">✎</button></div>`).join('');
 $('#main').innerHTML=`<div class="designer"><aside class="sidebar"><section class="panel-section"><h2 class="section-title">Pantallas <button data-add-view="screen">＋</button></h2><div class="screens">${list(p.screens,'▣')}</div><h2 class="section-title section-space">Maestras <button data-add-view="master">＋</button></h2><div class="screens">${list(p.masters,'▤')}</div><h2 class="section-title section-space">Pop-ups / Faceplates <button data-add-view="popup">＋</button></h2><div class="screens">${list(p.popups,'▢')}</div><div class="row-actions section-space"><button class="mini" data-action="duplicate-view">Duplicar vista</button><button class="mini danger" data-action="delete-view">Borrar</button></div></section><section class="panel-section"><h2 class="section-title">Biblioteca</h2><div class="tools">${C.KINDS.map(k=>`<button class="tool" draggable="true" data-kind="${k}"><b>${labels[k][0]}</b>${labels[k][1]}</button>`).join('')}</div></section><section class="panel-section"><h2 class="section-title">Imágenes <button data-action="add-image">＋</button></h2><div class="asset-list">${p.assets.map(a=>`<div class="asset-card" draggable="true" data-asset="${a.id}"><img src="${a.data}" alt=""><span>${esc(a.name)}</span></div>`).join('')}</div></section></aside>
 <section class="workspace"><div class="canvas-toolbar"><strong class="canvas-name">${esc(s.name)}</strong><span class="spacer"></span><button data-action="undo" ${S.history.length?'':'disabled'}>↶</button><button data-action="redo" ${S.future.length?'':'disabled'}>↷</button><button data-action="duplicate">Duplicar</button><button data-action="delete" class="danger">Borrar</button><button data-action="front">↑</button><button data-action="back">↓</button></div><div class="canvas-toolbar secondary"><button data-action="group">Agrupar</button><button data-action="ungroup">Desagrupar</button><select id="align-selection"><option value="">Alinear / distribuir…</option>${options([['left','Izquierda'],['right','Derecha'],['top','Arriba'],['bottom','Abajo'],['centerX','Centro horizontal'],['centerY','Centro vertical'],['distributeX','Distribuir horizontal'],['distributeY','Distribuir vertical']],'')}</select><span class="spacer"></span><label><input id="snap" type="checkbox" ${S.grid?'checked':''}>Rejilla</label><select id="zoom">${options([['0.25','25 %'],['0.5','50 %'],['0.75','75 %'],['1','100 %']],String(S.zoom))}</select><button data-action="fit">Ajustar</button></div><div class="canvas-scroll"><div class="canvas-wrap" id="canvas-wrap"><div id="stage" class="nx-stage editor-stage"></div></div></div></section><aside class="inspector" id="inspector"></aside></div>`;
 $('#snap').onchange=e=>{S.grid=e.target.checked;drawStage();};$('#zoom').onchange=e=>{S.zoom=Number(e.target.value);drawStage();};$('#align-selection').onchange=e=>align(e.target.value);
 $('#main').querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{S.screen=b.dataset.view;select([]);render();});$('#main').querySelectorAll('[data-add-view]').forEach(b=>b.onclick=()=>addView(b.dataset.addView));
 $('#main').querySelectorAll('[data-rename-view]').forEach(b=>b.onclick=()=>{const v=C.findView(p,b.dataset.renameView),name=prompt('Nombre',v.name);if(name?.trim())mutate(()=>v.name=name.trim().slice(0,80));});
 $('#main').querySelectorAll('[data-kind]').forEach(b=>{b.onclick=()=>addObject(b.dataset.kind);b.ondragstart=e=>e.dataTransfer.setData('application/x-hmi-nx',JSON.stringify({kind:b.dataset.kind}));});$('#main').querySelectorAll('[data-asset]').forEach(b=>{b.ondragstart=e=>e.dataTransfer.setData('application/x-hmi-nx',JSON.stringify({kind:'image',assetId:b.dataset.asset}));b.ondblclick=()=>addObject('image',40,40,b.dataset.asset);});drawStage();inspector();
}
function align(kind){const list=selectedObjects().filter(o=>!o.locked);if(list.length<2){toast('Selecciona al menos dos objetos desbloqueados');return;}mutate(()=>{const left=Math.min(...list.map(o=>o.x)),right=Math.max(...list.map(o=>o.x+o.w)),top=Math.min(...list.map(o=>o.y)),bottom=Math.max(...list.map(o=>o.y+o.h));if(kind.startsWith('distribute')){const axis=kind==='distributeX'?'x':'y',size=axis==='x'?'w':'h';list.sort((a,b)=>a[axis]-b[axis]);const start=list[0][axis],end=list.at(-1)[axis]+list.at(-1)[size],space=(end-start-list.reduce((n,o)=>n+o[size],0))/(list.length-1);let at=start;for(const o of list){o[axis]=Math.round(at);at+=o[size]+space;}}
 else for(const o of list){if(kind==='left')o.x=left;if(kind==='right')o.x=right-o.w;if(kind==='top')o.y=top;if(kind==='bottom')o.y=bottom-o.h;if(kind==='centerX')o.x=Math.round((left+right-o.w)/2);if(kind==='centerY')o.y=Math.round((top+bottom-o.h)/2);}});}
function addView(kind){const name=prompt(kind==='master'?'Nombre de maestra':kind==='popup'?'Nombre de ventana':'Nombre de pantalla',kind==='master'?'Cabecera':kind==='popup'?'Ventana':'Pantalla '+(S.p.screens.length+1));if(!name?.trim())return;mutate(()=>{const v=C.newView(kind,name.trim().slice(0,80));v.width=kind==='popup'?480:S.p.width;v.height=kind==='popup'?360:S.p.height;S.p[kind==='master'?'masters':kind==='popup'?'popups':'screens'].push(v);S.screen=v.id;select([]);});}
function render(){if(!C.findView(S.p,S.screen))S.screen=S.p.screens[0].id;S.selection=S.selection.filter(id=>current().objects.some(o=>o.id===id));if(!S.selection.includes(S.selected))S.selected=S.selection.at(-1)||null;$('#project-name').value=S.p.name;$('#tag-count').textContent=S.p.variables.length;$('#project-summary').textContent=`${S.p.screens.length} pantallas · ${S.p.masters.length} maestras · ${S.p.popups.length} ventanas · ${S.p.variables.length} variables · v${S.p.revision}`;document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===S.tab));if(S.tab==='editor')designer();else NXPanels.render(S.tab,A);}
async function backupV1(raw){if(raw.schemaVersion===1){try{await store('readwrite',s=>s.put({id:raw.id+'-v1backup',name:raw.name+' · copia original v1',updated:Date.now(),project:raw,backup:true}));}catch{download(raw.name+'_original_v1.nxhmi',JSON.stringify(raw,null,2),'application/json');}}}
async function useProject(p){await saveNow();S.p=C.migrate(p);S.screen=S.p.screens[0].id;select([]);S.recipe=null;S.history=[];S.future=[];S.tab='editor';render();autosave();}
async function importImages(files,x=40,y=40){for(const f of [...files]){try{if(!['image/png','image/jpeg','image/webp','image/svg+xml'].includes(f.type)||f.size>4*1024*1024)throw new Error('Imagen no compatible o mayor de 4 MB');if(f.type==='image/svg+xml'){const text=await f.text(),doc=new DOMParser().parseFromString(text,'image/svg+xml');if(doc.querySelector('parsererror,script,foreignObject,iframe,object,embed')||/<!ENTITY|<!DOCTYPE/i.test(text))throw new Error('SVG no permitido');for(const n of doc.querySelectorAll('*'))for(const a of n.attributes)if(/^on/i.test(a.name)||(/href$/i.test(a.name)&&!a.value.startsWith('#')&&!/^data:image\/(png|jpeg|webp);base64,/.test(a.value)))throw new Error('SVG con referencias externas/eventos');if(/url\s*\(\s*["']?(?!#)/i.test(text))throw new Error('SVG con CSS externo');}
 const url=URL.createObjectURL(f),img=new Image();try{await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=()=>reject(new Error('No se pudo decodificar'));img.src=url;});if(!img.naturalWidth||img.naturalWidth*img.naturalHeight>64000000)throw new Error('Dimensiones demasiado grandes');const scale=Math.min(1,2048/img.naturalWidth,2048/img.naturalHeight),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(img.naturalWidth*scale));canvas.height=Math.max(1,Math.round(img.naturalHeight*scale));canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);const data=canvas.toDataURL('image/png');if(data.length>6*1024*1024||S.p.assets.reduce((n,a)=>n+a.data.length,0)+data.length>12*1024*1024)throw new Error('Límite 6 MB/recurso, 12 MB/proyecto');const asset={id:C.id(),name:f.name,data,width:canvas.width,height:canvas.height};mutate(()=>S.p.assets.push(asset));const o=selected();if(o?.kind==='image'&&!o.assetId)mutate(()=>o.assetId=asset.id);else addObject('image',x,y,asset.id);}finally{URL.revokeObjectURL(url);}}catch(e){toast(f.name+': '+e.message);}}}
function preview(real=false){const errors=C.validate(S.p);if(errors.length){modal('Revisa el proyecto',`<div class="error-list">${esc(errors.join('\n'))}</div>`);return;}if(real&&S.p.connection.profile!=='nx-http-v2'){toast('Selecciona el perfil NX HTTP v2 para probar el servicio.');return;}modal(real?'Runtime · servicio NX HTTP v2':'Simulación · usuarios de operación y servicios locales',`<div id="preview-host"></div>${real?'':`<details class="simulation-data"><summary>Inyectar valores simulados (no son órdenes de operador)</summary><div class="sim-grid">${S.p.variables.map(v=>`<label>${esc(v.name)} · ${v.type}${v.type==='BOOL'?`<select data-sim="${esc(v.name)}">${options([['false','FALSE'],['true','TRUE']],String(v.initial))}</select>`:`<input data-sim="${esc(v.name)}" type="${v.type==='STRING'?'text':'number'}" step="any" value="${esc(v.initial)}">`}</label>`).join('')}</div></details>`}`,true);const p=C.copy(S.p);if(real)p.connection.sameOrigin=false;S.runtime=new R.Runtime(p,$('#preview-host'),{simulate:!real});$('#modal-body').querySelectorAll('[data-sim]').forEach(input=>input.onchange=()=>{try{S.runtime.setSim(input.dataset.sim,input.value);}catch(e){toast(e.message);}});}
async function exportSD(){const errors=C.validate(S.p);if(errors.length){modal('No se puede exportar todavía',`<div class="error-list">${esc(errors.join('\n'))}</div>`);return;}modal('Exportar aplicación para SD',`<p><strong>${esc(S.p.name)}</strong> · ${S.p.connection.profile==='simulation'?'SIMULACIÓN':'Contrato NX HTTP v2'}</p><label class="field">Formato<select id="export-mode">${options([['single','HTML único autocontenido'],['split','Pantallas y recursos bajo demanda']],S.p.exportMode)}</select></label><div class="warning">No se incluye un FB HTTP Omron compilado. El contrato v2 requiere integración en el NX. Exportar no valida el hardware ni instala usuarios. La política de operación se entrega separada de SD/ para su instalación autorizada.</div><p class="hint">El modo por pantallas necesita servir varias rutas. Se comprueban las versiones de las vistas. No necesita CDN. Recetas operativas y registros no deben sobrescribirse al actualizar el paquete.</p><div id="export-result"></div><div class="modal-actions"><button id="download-export" class="primary">Generar ZIP</button></div>`);$('#download-export').onclick=async()=>{const b=$('#download-export');b.disabled=true;b.textContent='Generando…';try{const mode=$('#export-mode').value,p=C.copy(S.p);p.exportMode=mode;const result=await NXExporter.build(p,mode);download((p.name.replace(/[^A-Za-z0-9_-]/g,'_')||'HMI_NX')+'_'+mode+'_SD.zip',result.zip,'application/zip');$('#export-result').textContent=`Paquete ${result.buildId} · ${(result.bytes/1024).toFixed(0)} kB · ${Object.keys(result.files).length} archivos`;b.textContent='Descargar de nuevo';b.disabled=false;}catch(e){toast(e.message);b.textContent='Reintentar';b.disabled=false;}};}
function pasteObjects(){if(!S.clipboard.length)return;mutate(()=>{const ids=[],groups=new Map(),s=current();for(const source of S.clipboard){const o=C.copy(source);o.id=C.id();o.w=Math.min(s.width,o.w);o.h=Math.min(s.height,o.h);o.x=Math.min(s.width-o.w,o.x+20);o.y=Math.min(s.height-o.h,o.y+20);if(o.groupId){if(!groups.has(o.groupId))groups.set(o.groupId,C.id());o.groupId=groups.get(o.groupId);}s.objects.push(o);ids.push(o.id);}select(ids);});}
const actions={
 'close-modal':closeModal,preview:()=>preview(false),export:exportSD,'add-image':()=>$('#image-file').click(),
 save:()=>{saveNow();download(S.p.name.replace(/[^A-Za-z0-9_-]/g,'_')+'.nxhmi',JSON.stringify(S.p,null,2),'application/json');},open:()=>$('#project-file').click(),
 new:()=>{modal('Nuevo proyecto',`<p>El proyecto actual se conserva en este navegador.</p><div class="modal-actions"><button id="new-demo">Demo completa</button><button id="new-empty" class="primary">Proyecto vacío</button></div>`);$('#new-demo').onclick=()=>{closeModal();useProject(C.demoProject());};$('#new-empty').onclick=()=>{closeModal();useProject(C.newProject());};},
 'duplicate-view':()=>mutate(()=>{const s=C.copy(current()),old=s.id;s.id=C.id();s.name+=' copia';s.objects.forEach(o=>{o.id=C.id();o.groupId='';if(o.targetScreen===old)o.targetScreen=s.id;});S.p[s.kind==='screen'?'screens':s.kind==='master'?'masters':'popups'].push(s);S.screen=s.id;select([]);}),
 'delete-view':()=>{const s=current();if(s.kind==='screen'&&S.p.screens.length===1){toast('Debe quedar una pantalla');return;}if(C.allViews(S.p).some(v=>v.masterId===s.id||v.objects.some(o=>o.targetScreen===s.id))){toast('La vista se utiliza: elimina primero sus referencias');return;}if(confirm('¿Eliminar '+s.name+'?'))mutate(()=>{const key=s.kind==='screen'?'screens':s.kind==='master'?'masters':'popups';S.p[key]=S.p[key].filter(v=>v!==s);S.screen=S.p.screens[0].id;select([]);});},
 duplicate:()=>{S.clipboard=C.copy(selectedObjects());pasteObjects();},copy:()=>{S.clipboard=C.copy(selectedObjects());toast('Objetos copiados');},paste:pasteObjects,
 delete:()=>{if(S.selection.length)mutate(()=>{current().objects=current().objects.filter(o=>!S.selection.includes(o.id)||o.locked);select([]);});},
 front:()=>mutate(()=>{const list=selectedObjects();current().objects=[...current().objects.filter(o=>!list.includes(o)),...list];}),back:()=>mutate(()=>{const list=selectedObjects();current().objects=[...list,...current().objects.filter(o=>!list.includes(o))];}),
 group:()=>{if(S.selection.length<2)return;mutate(()=>{const id=C.id();for(const o of selectedObjects())o.groupId=id;});},ungroup:()=>mutate(()=>selectedObjects().forEach(o=>o.groupId='')),
 undo:()=>{if(S.history.length){S.future.push(JSON.stringify(S.p));S.p=JSON.parse(S.history.pop());select([]);autosave();render();}},redo:()=>{if(S.future.length){S.history.push(JSON.stringify(S.p));S.p=JSON.parse(S.future.pop());select([]);autosave();render();}},fit:()=>{S.zoom=Math.max(.15,Math.min(1,($('.canvas-scroll').clientWidth-56)/current().width));drawStage();}
};
const A={S,C,R,$,esc,el,toast,modal,closeModal,options,mutate,render,download,store,useProject,preview,saveNow,backupV1};window.NXApp=A;
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(b&&actions[b.dataset.action]){try{Promise.resolve(actions[b.dataset.action]()).catch(err=>toast(err.message));}catch(err){toast(err.message);}return;}const tab=e.target.closest('[data-tab],[data-go]');if(tab){S.tab=tab.dataset.tab||tab.dataset.go;render();}});
$('#project-name').onchange=e=>{const name=e.target.value.trim();if(name)mutate(()=>S.p.name=name.slice(0,100));};$('#modal').addEventListener('cancel',e=>{e.preventDefault();closeModal();});
$('#project-file').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>20*1024*1024)throw new Error('Proyecto mayor de 20 MB');const text=await f.text(),p=C.parseProject(text,false);await backupV1(JSON.parse(text));await useProject(p);toast('Proyecto cargado'+(p.migration?' y migrado conservando el original.':'.'));}catch(err){toast(err.message);}e.target.value='';};$('#image-file').onchange=async e=>{await importImages(e.target.files);e.target.value='';};
document.addEventListener('keydown',e=>{if($('#modal').open||['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName))return;const cmd=e.ctrlKey||e.metaKey,key=e.key.toLowerCase();if(cmd&&key==='z'){e.preventDefault();actions[e.shiftKey?'redo':'undo']();}else if(cmd&&key==='s'){e.preventDefault();actions.save();}else if(S.tab==='editor'&&cmd&&['d','c','v','a'].includes(key)){e.preventDefault();if(key==='a'){select(current().objects.map(o=>o.id));drawStage();inspector();}else actions[{d:'duplicate',c:'copy',v:'paste'}[key]]();}else if(e.key==='Delete'&&S.tab==='editor'){e.preventDefault();actions.delete();}else if(S.tab==='editor'&&S.selection.length&&['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();const step=e.shiftKey?10:1;mutate(()=>{for(const o of selectedObjects().filter(o=>!o.locked)){o.x=Math.max(0,Math.min(current().width-o.w,o.x+(e.key==='ArrowRight'?step:e.key==='ArrowLeft'?-step:0)));o.y=Math.max(0,Math.min(current().height-o.h,o.y+(e.key==='ArrowDown'?step:e.key==='ArrowUp'?-step:0)));}});}});
window.addEventListener('pagehide',()=>{if(S.runtime)S.runtime.stop();});
(async()=>{try{const active=localStorage.getItem('HMI_NX_active');if(active){const row=await store('readonly',s=>s.get(active));if(row?.project){const p=C.parseProject(JSON.stringify(row.project),false);await backupV1(row.project);S.p=p;S.screen=p.screens[0].id;}}}catch(e){toast('Almacenamiento local no disponible: '+e.message);}render();})();
})();
