/* Bounded tabular exports. CSV formula injection guarded; XLSX cells use literal values. */
(function(root){
'use strict';const C=root.NXCore,xml=s=>String(s??'').replace(/[\x00-\x08\x0B\x0C\x0E-\x1F]/g,'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
const printable=v=>v==null?'':typeof v==='object'?JSON.stringify(v):String(v);
function csv(rows){return '\uFEFF'+rows.map(row=>row.map(v=>{let s=printable(v);if(typeof v!=='number'&&/^[\s]*[=+\-@]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';}).join(';')).join('\r\n');}
function xlsx(rows,title='Datos HMI'){
 const cellName=n=>{let s='';for(n++;n;n=Math.floor((n-1)/26))s=String.fromCharCode(65+(n-1)%26)+s;return s;};
 const width=rows[0]?.length||1,max=Math.max(1,rows.length);
 const sheet=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><dimension ref="A1:${cellName(width-1)}${max}"/><sheetViews><sheetView workbookViewId="0"><pane ySplit="1" topLeftCell="A2" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><cols>${Array.from({length:width},(_,i)=>`<col min="${i+1}" max="${i+1}" width="${Math.min(40,Math.max(18,String(rows[0]?.[i]||'').length+5))}" customWidth="1"/>`).join('')}</cols><sheetData>${rows.map((row,r)=>`<row r="${r+1}" ht="${r===0?28:22}" customHeight="1">${row.map((v,c)=>{const at=cellName(c)+(r+1),style=r===0?1:0;return typeof v==='number'&&Number.isFinite(v)?`<c r="${at}" s="${style}"><v>${v}</v></c>`:`<c r="${at}" s="${style}" t="inlineStr"><is><t xml:space="preserve">${xml(printable(v).slice(0,32767))}</t></is></c>`;}).join('')}</row>`).join('')}</sheetData><autoFilter ref="A1:${cellName(width-1)}${max}"/></worksheet>`;
 return C.zip({
 '[Content_Types].xml':'<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/></Types>',
 '_rels/.rels':'<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>',
 'xl/workbook.xml':`<?xml version="1.0"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="${xml(title.replace(/[\\/*?:\[\]]/g,' ').slice(0,31))}" sheetId="1" r:id="rId1"/></sheets></workbook>`,
 'xl/_rels/workbook.xml.rels':'<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>',
 'xl/styles.xml':'<?xml version="1.0"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="2"><font><sz val="11"/><name val="Calibri"/></font><font><b/><sz val="11"/><color rgb="FFFFFFFF"/><name val="Calibri"/></font></fonts><fills count="3"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF153750"/><bgColor indexed="64"/></patternFill></fill></fills><borders count="1"><border/></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="2"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/><xf numFmtId="0" fontId="1" fillId="2" borderId="0" xfId="0" applyFont="1" applyFill="1"/></cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles></styleSheet>',
 'xl/worksheets/sheet1.xml':sheet});
}
function download(name,data,type='application/octet-stream'){const url=URL.createObjectURL(new Blob([data],{type})),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
function records(kind,rows){
 if(kind==='alarms')return [['ID aparición','Código','Mensaje','Prioridad','Activación UTC','Cese UTC','Activa','Reconocida','Usuario ACK','Fecha ACK UTC','Silenciada'],...rows.map(r=>[r.id,r.code,r.name,r.severity,new Date(r.time).toISOString(),r.cleared?new Date(r.cleared).toISOString():'',r.active,r.ack,r.ackBy,r.ackAt?new Date(r.ackAt).toISOString():'',r.silenced])];
 return [['ID','Fecha UTC','Usuario','Acción','Destino','Valor anterior','Solicitud','Aplicado','Resultado','Comando'],...rows.map(r=>[r.id,new Date(r.time).toISOString(),r.user,r.action,r.target,r.before,r.requested,r.applied,r.result,r.commandId])];
}
root.NXData={csv,xlsx,download,records};
})(globalThis);
