/* SD package exporter. Split packages load only requested screens/assets, with version checks. */
(function(root){
'use strict';const C=root.NXCore;
const runtimeFiles=['core.js','model.js','service.js','data.js','widgets.js','transport.js','runtime.js'];
const safe=x=>JSON.stringify(x).replace(/</g,'\\u003c').replace(/\u2028/g,'\\u2028').replace(/\u2029/g,'\\u2029');
async function build(project,mode,provided=null){
 const p=C.migrate(project),errors=C.validate(p);if(errors.length)throw new Error(errors.join('\n'));if(!['single','split'].includes(mode))throw new Error('Modo de exportación no válido');
 const sources=provided||Object.fromEntries(await Promise.all(['style.css',...runtimeFiles].map(async name=>{const r=await fetch(name,{cache:'no-store'});if(!r.ok)throw new Error('No se pudo cargar '+name);return [name,await r.text()];})));
 const buildId=C.digest(C.canonical({project:p,files:Object.fromEntries(Object.entries(sources).map(([k,v])=>[k,C.digest(v)]))})).slice(0,24),files={},policyHash=C.policyDigest(p),app=C.copy(p);
 app._deployment={buildId,policyDigest:policyHash,mode,version:'0.2.0'};
 if(mode==='split'){
  if(p.connection.profile==='simulation')app._deployment.simulationPolicy={digest:policyHash,elements:[...C.policyObjects(p).values()]};
  const bundle=runtimeFiles.map(f=>sources[f]).join('\n');files[`SD/builds/${buildId}/runtime.js`]=bundle;files[`SD/builds/${buildId}/style.css`]=sources['style.css'];
  for(const key of ['screens','masters','popups'])app[key]=app[key].map(view=>{const name=`builds/${buildId}/views/${view.id}.json`,text=JSON.stringify({buildId,view});files['SD/'+name]=text;return {id:view.id,name:view.name,kind:view.kind,width:view.width,height:view.height,background:view.background,masterId:view.masterId,slots:view.slots,path:name,hash:C.digest(text)};});
  app.assets=app.assets.map(asset=>{const match=asset.data.match(/^data:image\/(png|jpeg|webp);base64,(.*)$/),extension=match[1]==='jpeg'?'jpg':match[1],path=`builds/${buildId}/assets/${asset.id}.${extension}`,binary=typeof atob==='function'?Uint8Array.from(atob(match[2]),x=>x.charCodeAt(0)):new Uint8Array(Buffer.from(match[2],'base64'));files['SD/'+path]=binary;const {data,...meta}=asset;return {...meta,url:path};});
 }
 const head=`<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="referrer" content="no-referrer"><meta name="robots" content="noindex"><title>${C.esc(app.name)}</title>`;
 const style=mode==='single'?`<style>${sources['style.css']}</style>`:`<link rel="stylesheet" href="builds/${buildId}/style.css">`;
 const scripts=mode==='single'?`<script>${runtimeFiles.map(f=>sources[f]).join('\n')}<\/script>`:`<script src="builds/${buildId}/runtime.js"><\/script>`;
 files['SD/index.html']=head+style+'</head><body class="nx-exported"><div id="hmi"></div>'+scripts+`<script>const project=${safe(app)};window.hmiRuntime=new NXRuntime.Runtime(project,document.getElementById('hmi'));<\/script></body></html>`;
 files['project.nxhmi']=JSON.stringify(p,null,2);
 files['Sysmac/variables.csv']=NXData.csv([['Nombre Sysmac','Tipo','Acceso','Máx. texto','Frecuencia objetivo ms','Global','Mínimo','Máximo','Unidad','Comentario'],...p.variables.map(v=>[v.name,v.type,v.access,v.maxLength,v.rateMs,v.global,v.min,v.max,v.unit,v.comment])]);
 files['Engineering/operation-policy.json']=JSON.stringify({policyDigest:policyHash,policy:C.policy(p)},null,2);
 files['Engineering/transport-contract.json']=JSON.stringify(C.apiContract,null,2);
 files['Engineering/manifest.json']=JSON.stringify({version:'0.2.0',buildId,projectId:p.id,policyDigest:policyHash,mode,device:'NX102',hardwareValidated:false,requirements:mode==='split'?[...C.apiContract.capabilities]:C.apiContract.capabilities.filter(x=>x!=='assetFiles'),paths:Object.keys(files).filter(n=>n.startsWith('SD/'))},null,2);
 files['LEEME.txt']=`HMI NX 0.2 — paquete ${buildId}\n\nPerfil: ${p.connection.profile}\nFormato: ${mode}\n\nCopiar únicamente el contenido SD/ al directorio de recursos admitido por el servidor del equipo. No se incluye un FB HTTP Omron compilado. NX HTTP v2 es un contrato propio; no es el protocolo verificado de WebServer_NJ_NX v3.5. El runtime no se conecta a un NX solo por copiar el HTML.\n\nModo single: HTML autocontenido. Modo split: index.html + carpeta builds/${buildId}; las vistas y sus imágenes se cargan bajo demanda. Subir primero builds y sustituir index al final. Mantener la versión anterior para sesiones abiertas y rollback.\n\nEngineering/ NO va en el directorio web público: su política es una propuesta de ingeniería, que el servicio de máquina debe instalar mediante un procedimiento autorizado. Editar el HTML no cambia la política instalada. Las contraseñas no se guardan en el proyecto ni en la SD pública. Para operar con sesiones reales se requiere un servicio autenticado con HTTPS; el FB web genérico no aporta esos servicios automáticamente.\n\nLos usuarios/roles son de OPERACIÓN. No hay cuentas ni permisos del editor. Sin multidriver ni tendencias.\n\nLa simulación permite elegir un rol sin contraseña: no es autenticación industrial. El servidor de referencia del repositorio es exclusivamente un banco de pruebas, no código que ejecute el NX102. Alarmas/históricos/recetas duraderos en el NX requieren integrar su captura/persistencia y el transporte real. No confundir las pruebas del banco con validación PLC.\n\nLas alarmas tienen ACK/silencio/reset separados. ACK no rearma una máquina. Las recetas se validan por lote y versión. Los comandos desconocidos no se reintentan. Los permisos, condiciones y rangos se verifican en el servicio instalado. Una condición gráfica no sustituye enclavamientos ni seguridad PLC.\n\nMedir latencia, límites de SD, carga del PLC, pérdida de comunicación y concurrencia en un NX102 aislado antes de producción. No usar para seguridad funcional, emergencia o jog mantenido. Guardar recetas/registros fuera del directorio de builds y preservar esos datos al actualizar la interfaz.\n`;
 return {files,zip:C.zip(files),buildId,policyDigest:policyHash,bytes:Object.values(files).reduce((n,v)=>n+(v instanceof Uint8Array?v.length:new TextEncoder().encode(v).length),0)};
}
root.NXExporter={build,runtimeFiles};
})(globalThis);
