/* Configuration panels. All projects/assets remain on the user's device. */
(function(root){
'use strict';
function render(tab,A){
 const {S,C,$,esc,options,mutate,toast,modal,closeModal,download}=A,p=S.p;
 const title=(name,description,actions='')=>`<div class="page-heading"><div><h1>${name}</h1><p>${description}</p></div><div class="row-actions">${actions}</div></div>`;
 const optionTags=value=>options([['','— Variable —'],...p.variables.map(v=>[v.name,`${v.name} · ${v.type}`])],value);
 const editValue=(v,value,attrs)=>v.type==='BOOL'?`<select ${attrs}>${options([['false','FALSE'],['true','TRUE']],String(value))}</select>`:`<input ${attrs} type="${v.type==='STRING'?'text':'number'}" step="any" value="${esc(value)}">`;
 const renameReferences=(from,to)=>{for(const s of p.screens)for(const o of s.objects){if(o.binding===from)o.binding=to;if(o.visibleBinding===from)o.visibleBinding=to;}for(const a of p.alarms)if(a.binding===from)a.binding=to;for(const r of p.recipes)if(Object.hasOwn(r.values,from)){r.values[to]=r.values[from];delete r.values[from];}};
 if(tab==='variables'){
  $('#main').innerHTML=`<div class="page">${title('Variables del PLC','Importa la tabla de Sysmac o crea variables manualmente. La importación no modifica el programa del NX.',`<button id="sample-vars">CSV de ejemplo</button><button id="import-vars">Importar CSV / pegar</button><button id="add-var" class="primary">＋ Variable</button>`)}
  <div class="info">Tipos V1: BOOL, DINT, REAL y STRING. Importación por CSV/TSV o filas copiadas de Sysmac: Nombre, Tipo de datos y Comentario. INT/UINT/estructuras requieren variables puente explícitas. El acceso importado empieza en <strong>solo lectura</strong>.</div>
  <div class="card table-wrap"><table><thead><tr><th>Nombre</th><th>Tipo</th><th>Acceso</th><th>Valor inicial (sim.)</th><th>Mínimo</th><th>Máximo</th><th>Comentario</th><th></th></tr></thead><tbody>${p.variables.map((v,i)=>`<tr data-var-row="${i}"><td><input data-v="name" aria-label="Nombre variable ${i+1}" value="${esc(v.name)}"></td><td><select data-v="type">${options(C.TYPES,v.type)}</select></td><td><select data-v="access">${options([['R','Lectura'],['RW','Lectura/escritura']],v.access)}</select></td><td>${editValue(v,v.initial,'data-v="initial"')}</td><td><input data-v="min" type="number" step="any" value="${esc(v.min??'')}" ${['BOOL','STRING'].includes(v.type)?'disabled':''}></td><td><input data-v="max" type="number" step="any" value="${esc(v.max??'')}" ${['BOOL','STRING'].includes(v.type)?'disabled':''}></td><td><input data-v="comment" value="${esc(v.comment)}"></td><td><button data-remove-var="${i}" class="danger" title="Borrar variable">✕</button></td></tr>`).join('')}</tbody></table>${p.variables.length?'':'<p class="muted">No hay variables. Importa una tabla o añade la primera.</p>'}</div><p class="hint">RW es permiso de proyecto, no protección del PLC. El servidor debe imponer su propia lista blanca, permisos y validación. El mapeo CSV es orientativo, no un FB compilable.</p></div>`;
  $('#sample-vars').onclick=()=>download('sysmac_variables_ejemplo.csv','Name;Data Type;Comment\nMachine.Running;BOOL;Estado de marcha\nProcess.Setpoint;REAL;Consigna\nProduction.Count;DINT;Contador\nProduct.Name;STRING[80];Nombre producto\n','text/csv;charset=utf-8');
  $('#add-var').onclick=()=>{const name=prompt('Nombre de variable (identificador Sysmac)','NewVariable');if(!name)return;if(!C.nameOK(name)||p.variables.some(v=>v.name===name)||p.variables.length>=100){toast('Nombre inválido/duplicado o límite de 100 variables.');return;}mutate(()=>p.variables.push({name,type:'BOOL',access:'R',initial:false,comment:''}));};
  $('#import-vars').onclick=()=>{
   modal('Importar variables de Sysmac',`<p>Pega las filas de variables de Sysmac o selecciona CSV/TSV. Se admite encabezado en español o inglés. No se abren archivos .smc2 ni XLSX en esta versión.</p><textarea id="variable-text" rows="12" placeholder="Name&#9;Data Type&#9;Comment"></textarea><div id="import-errors" class="error-list"></div><div class="modal-actions"><button id="choose-vars-file">Seleccionar archivo</button><button id="do-import" class="primary">Importar a este proyecto</button></div>`);
   $('#choose-vars-file').onclick=()=>$('#variables-file').click();$('#variables-file').onchange=async e=>{const f=e.target.files[0];if(f){if(f.size>1024*1024)toast('Tabla mayor de 1 MB');else $('#variable-text').value=await f.text();}e.target.value='';};
   $('#do-import').onclick=()=>{try{const vars=C.importVariables($('#variable-text').value,p.variables),count=vars.length-p.variables.length;mutate(()=>p.variables=vars);closeModal();toast(`${count} variables importadas. Revisa permisos de escritura.`);}catch(e){$('#import-errors').textContent=e.message;}};
  };
  $('#main').querySelectorAll('[data-var-row]').forEach(row=>row.querySelectorAll('[data-v]').forEach(input=>input.onchange=()=>{const v=p.variables[Number(row.dataset.varRow)],key=input.dataset.v;let value=input.value;try{
   if(key==='name'&&(!C.nameOK(value)||p.variables.some(a=>a!==v&&a.name===value)))throw new Error('Nombre no válido o duplicado');
   if(key==='initial')value=C.typed(v,value);
   if(key==='min'||key==='max'){value=value===''?'':Number(value);const test={...v,[key]:value};if(test.min!==''&&test.min!=null&&test.max!==''&&test.max!=null&&test.min>test.max)throw new Error('Rango invertido');C.typed(test,v.initial);}
   mutate(()=>{if(key==='name')renameReferences(v.name,value);v[key]=value;if(key==='type'){v.initial=value==='BOOL'?false:value==='STRING'?'':0;v.min='';v.max='';}});
  }catch(e){toast(e.message);A.render();}}));
  $('#main').querySelectorAll('[data-remove-var]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.removeVar),v=p.variables[i],used=p.screens.some(s=>s.objects.some(o=>o.binding===v.name||o.visibleBinding===v.name))||p.alarms.some(a=>a.binding===v.name)||p.recipes.some(r=>Object.hasOwn(r.values,v.name));if(used){toast('Variable utilizada: elimina o cambia primero sus enlaces, recetas y alarmas.');return;}mutate(()=>p.variables.splice(i,1));});
 }
 if(tab==='recipes'){
  const active=p.recipes.find(r=>r.id===S.recipe)||p.recipes[0];if(active)S.recipe=active.id;const writable=p.variables.filter(v=>v.access==='RW');
  $('#main').innerHTML=`<div class="page">${title('Recetas','Define conjuntos de parámetros y aplícalos como un lote.',`<button id="add-recipe" class="primary">＋ Receta</button>`)}<div class="warning">En simulación el lote se aplica completo. Con PLC, el adaptador debe validar y aplicar el lote de forma atómica. No se simula atomicidad mediante escrituras sueltas. Guardado de recetas en SD y gestión de versiones PLC no incluidos.</div><div class="split"><div class="record-list">${p.recipes.map(r=>`<button data-recipe="${esc(r.id)}" class="${r===active?'active':''}">☷ ${esc(r.name)}<br><small>${Object.keys(r.values).length} parámetros</small></button>`).join('')}</div><div class="card">${active?`<div class="page-heading"><label class="field">Nombre<input id="recipe-name" value="${esc(active.name)}"></label><div class="row-actions"><button id="copy-recipe">Duplicar</button><button id="delete-recipe" class="danger">Eliminar</button></div></div><div class="recipe-fields">${writable.map(v=>`<div class="recipe-field"><input type="checkbox" data-recipe-use="${esc(v.name)}" ${Object.hasOwn(active.values,v.name)?'checked':''}><span>${esc(v.name)} <small>${v.type}</small></span>${editValue(v,active.values[v.name]??v.initial,`data-recipe-value="${esc(v.name)}" ${Object.hasOwn(active.values,v.name)?'':'disabled'}`)}</div>`).join('')}</div><p class="hint">Solo aparecen variables RW. Marca los parámetros que debe modificar la receta.</p>`:'<p>Crea una receta y añade variables RW.</p>'}</div></div></div>`;
  $('#add-recipe').onclick=()=>{const name=prompt('Nombre de receta','Receta '+(p.recipes.length+1));if(name?.trim())mutate(()=>{const r={id:C.id(),name:name.trim(),values:{}};p.recipes.push(r);S.recipe=r.id;});};
  $('#main').querySelectorAll('[data-recipe]').forEach(b=>b.onclick=()=>{S.recipe=b.dataset.recipe;A.render();});
  if(active){$('#recipe-name').onchange=e=>mutate(()=>active.name=e.target.value.trim()||'Receta');$('#copy-recipe').onclick=()=>mutate(()=>{const r=C.copy(active);r.id=C.id();r.name+=' copia';p.recipes.push(r);S.recipe=r.id;});$('#delete-recipe').onclick=()=>{if(confirm('¿Eliminar esta receta?'))mutate(()=>p.recipes=p.recipes.filter(r=>r!==active));};
   $('#main').querySelectorAll('[data-recipe-use]').forEach(input=>input.onchange=()=>mutate(()=>{const name=input.dataset.recipeUse;if(input.checked)active.values[name]=p.variables.find(v=>v.name===name).initial;else delete active.values[name];}));
   $('#main').querySelectorAll('[data-recipe-value]').forEach(input=>input.onchange=()=>{try{const name=input.dataset.recipeValue,v=p.variables.find(v=>v.name===name),value=C.typed(v,input.value);mutate(()=>active.values[name]=value);}catch(e){toast(e.message);A.render();}});
  }
 }
 if(tab==='alarms'){
  $('#main').innerHTML=`<div class="page">${title('Alarmas','Condiciones evaluadas a partir de los valores leídos. También funcionan en simulación.',`<button id="add-alarm" class="primary">＋ Alarma</button>`)}<div class="info">La lista e histórico de esta V1 pertenecen a la sesión del navegador (máximo 200 eventos). Reconocer una alarma no resetea una condición ni envía un ACK al PLC. Se siguen evaluando las alarmas aunque cambies de pantalla.</div><div class="card table-wrap"><table><thead><tr><th>Mensaje</th><th>Variable</th><th>Condición</th><th>Umbral</th><th>Severidad</th><th></th></tr></thead><tbody>${p.alarms.map((a,i)=>`<tr data-alarm="${i}"><td><input data-a="name" value="${esc(a.name)}"></td><td><select data-a="binding">${optionTags(a.binding)}</select></td><td><select data-a="operator">${options([['eq','='],['gt','>'],['ge','≥'],['lt','<'],['le','≤']],a.operator)}</select></td><td><input data-a="value" value="${esc(a.value)}"></td><td><select data-a="severity">${options([['info','Información'],['warning','Aviso'],['high','Alta']],a.severity)}</select></td><td><button data-delete-alarm="${i}" class="danger">✕</button></td></tr>`).join('')}</tbody></table></div><p class="hint">Si falla la comunicación se conserva el último evento y se indica estado desconocido. No se declara la máquina libre de alarmas por falta de datos.</p></div>`;
  $('#add-alarm').onclick=()=>{if(!p.variables.length){toast('Crea primero una variable.');return;}mutate(()=>{const v=p.variables[0];p.alarms.push({id:C.id(),name:'Nueva alarma',binding:v.name,operator:'eq',value:v.type==='BOOL'?'true':v.initial,severity:'warning'});});};
  $('#main').querySelectorAll('[data-alarm]').forEach(row=>row.querySelectorAll('[data-a]').forEach(input=>input.onchange=()=>{const a=p.alarms[Number(row.dataset.alarm)];let value=input.value;try{if(input.dataset.a==='value'){const v=p.variables.find(v=>v.name===a.binding);value=C.typed({...v,min:'',max:''},value);}mutate(()=>{a[input.dataset.a]=value;if(input.dataset.a==='binding'){const v=p.variables.find(v=>v.name===value);a.value=v?.type==='BOOL'?'true':v?.initial??0;a.operator='eq';}});}catch(e){toast(e.message);A.render();}}));
  $('#main').querySelectorAll('[data-delete-alarm]').forEach(b=>b.onclick=()=>mutate(()=>p.alarms.splice(Number(b.dataset.deleteAlarm),1)));
 }
 if(tab==='connection'){
  const c=p.connection;
  $('#main').innerHTML=`<div class="page">${title('Conexión NX102','Configura el destino y el perfil del runtime exportado.',`<button id="test-adapter">Probar adaptador</button>`)}<div class="warning"><strong>Integración PLC pendiente de validar.</strong> NX HTTP v1 es un contrato propio documentado, no el protocolo confirmado de la librería Omron. Es necesario implementar y probar el adaptador en el servidor/PLC. Introducir la IP por sí solo no conecta las variables.</div><div class="form-grid"><div class="card"><h3>Comunicaciones</h3><div class="form-grid"><label class="wide">Perfil<select id="connection-profile">${options([['simulation','Simulación (sin PLC)'],['nx-http-v1','NX HTTP v1 · requiere adaptador']],c.profile)}<option disabled>WebServer_NJ_NX 3.5 · driver pendiente de verificar</option></select></label><label class="wide">IP / URL del NX o puente local<input id="base-url" value="${esc(c.baseUrl)}" placeholder="http://192.168.250.1:81"></label><label>Intervalo de lectura (ms)<input id="poll-ms" type="number" min="100" max="10000" step="50" value="${c.pollMs}"></label><label>Timeout (ms)<input id="timeout-ms" type="number" min="300" max="30000" step="100" value="${c.timeoutMs}"></label><label class="check-line wide"><input id="same-origin" type="checkbox" ${c.sameOrigin?'checked':''}>En SD, usar el mismo origen que sirve el HTML (recomendado)</label><label class="check-line wide"><input id="allow-writes" type="checkbox" ${c.allowWrites?'checked':''}>Permitir habilitar escrituras en el runtime</label></div><p class="hint">La prueba desde el editor usa la IP configurada. El HTML exportado puede usar su propio origen. Las escrituras reales arrancan deshabilitadas en cada sesión.</p></div><div class="card"><h3>Proyecto y lienzo</h3><div class="form-grid"><label>Ancho (px)<input id="project-width" type="number" value="${p.width}" min="240" max="3840"></label><label>Alto (px)<input id="project-height" type="number" value="${p.height}" min="240" max="3840"></label></div><p class="hint">No se acepta una resolución que deje objetos fuera del lienzo.</p><div class="info">Una petición de lectura agrupada por ciclo, sin solapamiento. Las escrituras se envían al pulsar y no se reintentan automáticamente. Un intervalo de 100 ms es una consigna de polling, no una garantía.</div><button id="contract-download">Descargar contrato de API</button></div></div><div class="card"><h3>Condiciones de uso</h3><p class="hint">El editor alojado en HTTPS no debe rebajar la seguridad del navegador para acceder a un NX HTTP. Sirve el runtime desde el propio NX o utiliza un puente HTTPS autorizado, con permisos de red local/CORS cuando correspondan. No expongas el PLC a Internet. No se incluye FTP, despliegue remoto ni servidor HTTPS en el PLC.</p></div></div>`;
  const commitConnection=()=>{try{const next={profile:$('#connection-profile').value,baseUrl:new URL($('#base-url').value).origin,sameOrigin:$('#same-origin').checked,allowWrites:$('#allow-writes').checked,pollMs:Number($('#poll-ms').value),timeoutMs:Number($('#timeout-ms').value)};
   const test=C.newProject();test.connection=next;const errors=C.validate(test);if(errors.length)throw new Error(errors.join('\n'));mutate(()=>p.connection=next);
  }catch(e){toast(e.message);A.render();}};
  for(const id of ['connection-profile','base-url','same-origin','allow-writes','poll-ms','timeout-ms'])$('#'+id).onchange=commitConnection;
  for(const [id,key] of [['project-width','width'],['project-height','height']])$('#'+id).onchange=e=>{const n=Number(e.target.value);if(!Number.isInteger(n)||n<240||n>3840||p.screens.some(s=>s.objects.some(o=>key==='width'?o.x+o.w>n:o.y+o.h>n))){toast('Resolución no válida o deja objetos fuera del lienzo.');A.render();return;}mutate(()=>p[key]=n);};
  $('#contract-download').onclick=()=>download('nx-http-v1-contract.json',JSON.stringify(C.apiContract,null,2));$('#test-adapter').onclick=()=>A.preview(true);
 }
 if(tab==='projects'){
  $('#main').innerHTML=`<div class="page">${title('Mis proyectos locales','Guardado automático en este navegador. Descarga .nxhmi como copia de seguridad.',`<button data-action="open">Importar proyecto</button><button data-action="new" class="primary">＋ Proyecto</button>`)}<div class="warning">Esta primera versión no incluye cuentas, sincronización en nube ni control de licencias. Borrar los datos del navegador puede borrar estos proyectos. El código publicado no contiene tus diseños: permanecen en el dispositivo.</div><div class="project-cards" id="project-list">Cargando…</div></div>`;
  A.store('readonly',s=>s.getAll()).then(rows=>{if(S.tab!=='projects')return;rows.sort((a,b)=>b.updated-a.updated);$('#project-list').innerHTML=rows.map(row=>`<div class="card"><h3>${esc(row.name)}</h3><p class="muted">${new Date(row.updated).toLocaleString()}</p><p class="hint">${row.project.screens.length} pantallas · ${row.project.variables.length} variables</p><div class="row-actions"><button data-open-project="${esc(row.id)}">Abrir</button><button data-delete-project="${esc(row.id)}" class="danger" ${row.id===p.id?'disabled':''}>Eliminar</button></div></div>`).join('')||'Sin proyectos guardados.';
   $('#project-list').querySelectorAll('[data-open-project]').forEach(b=>b.onclick=()=>{try{const row=rows.find(r=>r.id===b.dataset.openProject),project=C.parseProject(JSON.stringify(row.project),false);A.useProject(project);}catch(e){toast(e.message);}});
   $('#project-list').querySelectorAll('[data-delete-project]').forEach(b=>b.onclick=async()=>{if(confirm('¿Eliminar este proyecto del navegador?')){await A.store('readwrite',s=>s.delete(b.dataset.deleteProject));A.render();}});
  }).catch(e=>toast(e.message));
 }
 if(tab==='help'){
  $('#main').innerHTML=`<div class="page guide">${title('De un lienzo vacío a una HMI exportada','Guía de la preview técnica 0.1. No es un producto industrial certificado.')}
  <div class="card"><h2>1. Prepara el proyecto</h2><p>Pulsa <strong>Nuevo → Proyecto vacío</strong> o usa la demo. En <strong>Conexión NX</strong> ajusta resolución, IP/puerto y frecuencia de consulta. Empieza en simulación.</p><h2>2. Importa las variables</h2><p>Copia la tabla de variables de Sysmac o importa un CSV/TSV desde <strong>Variables</strong>. Revisa nombres, tipos, comentarios, rangos y permisos RW. Para tipos no soportados utiliza variables puente en el PLC. La tabla exportada no genera automáticamente ese mapeo.</p><h2>3. Compón las pantallas</h2><p>Añade pantallas, arrastra objetos, ajusta tamaño con la esquina y define propiedades a la derecha. Un botón puede escribir un valor o cambiar de pantalla. Las imágenes se incorporan al proyecto; un SVG se convierte a PNG para excluir contenido activo. Las animaciones básicas son parpadeo y rotación.</p><h2>4. Recetas y alarmas</h2><p>Una receta agrupa parámetros RW. Una alarma compara una variable con un umbral. Coloca los objetos Recetas y Alarmas en cualquier pantalla. Los eventos y reconocimientos de alarma son locales a cada sesión, no históricos del PLC.</p><h2>5. Simula antes de exportar</h2><p>Pulsa <strong>Simular</strong> y abre el panel de variables ficticias. Comprueba navegación, lámparas, entradas, barras, recetas y alarmas. No hay comunicación con el PLC en ese modo.</p><h2>6. Exporta el ZIP</h2><pre>SD/index.html                  HMI autocontenida\nproject.nxhmi                  proyecto editable\nSysmac/variables.csv           tabla orientativa\nSysmac/transport-contract.json contrato propio HTTP\nLEEME.txt                      límites y puesta en servicio</pre><p>El runtime no necesita librerías de Internet. Copia el HTML a la ruta admitida por el FB que sirva páginas en el NX. El exportador no transfiere la SD ni instala el programa PLC.</p><h2>7. Valida el transporte real</h2><p><strong>NX HTTP v1 no es un driver verificado de WebServer_NJ_NX.</strong> Implementa el contrato del paquete, o desarrolla el adaptador de la librería Omron a partir de su protocolo real. El runtime exige datos tipados y confirmación de todo el lote escrito; no inventa respuestas ni usa simulación al perder conexión.</p><p>En una máquina, prueba carga del PLC, pérdida de conexión, datos obsoletos, rangos, conflictos de clientes, latencia, reinicio y recuperación. Mantén la lógica y seguridad en el PLC. Esta versión no admite jog mantenido, seguridad funcional ni ACK industrial de alarmas.</p><h2>Atajos</h2><p>Ctrl/Cmd+Z: deshacer · Ctrl/Cmd+Shift+Z: rehacer · Ctrl/Cmd+D: duplicar · Supr: borrar · Flechas: mover 1 px · Shift+Flechas: 10 px · Ctrl/Cmd+S: descargar proyecto.</p><h2>Privacidad y acceso</h2><p>No se envían variables, imágenes ni diseños a GitHub o a una base de datos. Los proyectos se guardan en IndexedDB del navegador. No hay autenticación ni protección comercial del editor en esta preview; esas funciones necesitan una siguiente fase con permisos de servidor.</p></div></div>`;
 }
}
root.NXPanels={render};
})(globalThis);
