'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto');
require('../core.js');const oldDemo=NXCore.demoProject();require('../model.js');const C=NXCore;
test('v1 migration is pure and new projects validate',()=>{const original=JSON.stringify(oldDemo),p=C.migrate(oldDemo);assert.equal(p.schemaVersion,2);assert.equal(JSON.stringify(oldDemo),original);assert.deepEqual(C.validate(p),[]);assert.deepEqual(C.validate(C.demoProject()),[]);assert.deepEqual(C.validate(C.newProject()),[]);});
test('package SHA256 agrees with Node for unicode, blocks and empty input',()=>{for(const s of ['', 'abc','á🙂'.repeat(64),'z'.repeat(10000)])assert.equal(C.digest(s),crypto.createHash('sha256').update(s).digest('hex'));});
test('Sysmac imports declared string capacity and rejects silent truncation',()=>{const v=C.importVariables('Name;Data Type;Comment\nLabel;STRING[80];texto');assert.equal(v[0].maxLength,80);assert.throws(()=>C.typed(v[0],'a'.repeat(81)));assert.throws(()=>C.importVariables('Name;Data Type\nLabel;STRING[500]'));});
test('dependencies include master/global/popup, not unrelated screens or alarm sources',()=>{const p=C.demoProject();p.variables.push({name:'Master.Value',type:'DINT',access:'R',initial:1,rateMs:1000,global:false,maxLength:255},{name:'Always.Value',type:'DINT',access:'R',initial:2,rateMs:1000,global:true,maxLength:255},{name:'Popup.Value',type:'REAL',access:'R',initial:2,rateMs:250,global:false,maxLength:255});const a=C.newObject('value');a.binding='Master.Value';a.writeBinding='';p.masters[0].objects.push(a);const pop=p.popups[0],b=C.newObject('value');b.binding='Popup.Value';b.writeBinding='';pop.objects.push(b);let names=C.dependencies(p,p.screens[0].id).map(v=>v.name);assert.ok(names.includes('Master.Value'));assert.ok(names.includes('Always.Value'));assert.ok(!names.includes('Machine.Fault'));assert.ok(!names.includes('Popup.Value'));names=C.dependencies(p,p.screens[0].id,[{id:pop.id,bindings:{run:'Machine.Running'},context:'opener'}]).map(v=>v.name);assert.ok(names.includes('Popup.Value'));});
test('faceplate command IDs resolve to installed exact variables',()=>{const p=C.demoProject(),opener=p.screens[0].objects.find(o=>o.action==='popup'),child=p.popups[0].objects.find(o=>o.kind==='switch'),map=C.policyObjects(p),o=map.get(opener.id+'::'+child.id);assert.equal(o.binding,'Machine.Running');assert.equal(o.writeBinding,'Machine.Running');p.variables.find(v=>v.name==='Machine.Running').access='R';assert.ok(C.validate(p).some(x=>x.includes('RW')));});
test('project files cannot carry production credentials or prototype keys',()=>{const p=C.demoProject();p.security.password='not-a-production-value';assert.ok(C.validate(p).some(e=>e.includes('credenciales')));assert.throws(()=>C.parseProject('{"__proto__":{}}'));});
test('policy digest changes when operation permissions change',()=>{const p=C.demoProject(),first=C.policyDigest(p);p.screens[0].objects.find(o=>o.kind==='button').operateRoles=['admin'];assert.notEqual(C.policyDigest(p),first);assert.equal(C.roleAllowed(['operator'],null),false);assert.equal(C.roleAllowed(['*'],null),true);});
test('unsupported features do not appear as drivers or trend objects',()=>{assert.ok(!C.KINDS.includes('trend'));assert.equal(C.apiContract.protocol,'nx-http-v2');assert.match(C.apiContract.notice,/No es WebServer/);});

test('role-aware polling excludes private view elements without breaking public polling',()=>{const p=C.demoProject(),o=p.screens[0].objects.find(o=>o.kind==='value');o.readRoles=['admin'];assert.ok(!C.dependencies(p,p.screens[0].id,[],null).some(v=>v.name===o.binding));assert.ok(C.dependencies(p,p.screens[0].id,[],'admin').some(v=>v.name===o.binding));});
