'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');require('../core.js');require('../model.js');require('../service.js');const C=NXCore,{MachineService}=NXService;
function rig(modify=()=>{},options={}){const p=C.demoProject();modify(p);let now=100000;const service=new MachineService(p,{clock:()=>now,...options});const user=role=>service.newSession({id:role,name:role,role}).token;const operator=user('operator'),maintenance=user('maintenance'),observer=user('observer');let sequence=0;const request=(o,action,data,revision=service.state.revision)=>({commandId:'test-command-'+(++sequence),policyDigest:service.hash,elementId:o.elementId||o.id,action,expectedRevision:revision,data});const obj=(kind,condition=()=>true)=>p.screens.flatMap(s=>s.objects).find(o=>o.kind===kind&&condition(o));return{p,service,user,operator,maintenance,observer,request,obj,advance:ms=>{now+=ms;service.tick();}};}
test('authorization is installed server-side, not the browser role label',()=>{const r=rig(),button=r.obj('button',o=>o.action==='write');assert.throws(()=>r.service.command('',r.request(button,'write',{value:true})),/Identif/);assert.throws(()=>r.service.command(r.observer,r.request(button,'write',{value:true})),/Permiso/);const req=r.request(button,'write',{value:true});req.role='admin';assert.throws(()=>r.service.command(r.observer,req),/Permiso/);assert.equal(r.service.state.values['Machine.Running'],false);});
test('fixed button values and independently installed policy are enforced',()=>{const r=rig(),button=r.obj('button',o=>o.binding==='Machine.Running'&&o.writeValue==='true');assert.throws(()=>r.service.command(r.operator,r.request(button,'write',{value:false})),/distinto/);const req=r.request(button,'write',{value:true});req.policyDigest='modified';assert.throws(()=>r.service.command(r.operator,req),/Política/);});
test('same command retry returns result exactly once; changed payload rejected',()=>{const r=rig(),o=r.obj('button',o=>o.binding==='Machine.Running'),req=r.request(o,'write',{value:true}),first=r.service.command(r.operator,req);assert.equal(first.applied,true);assert.deepEqual(r.service.command(r.operator,req),first);assert.equal(r.service.state.revision,1);assert.equal(r.service.state.audit.filter(a=>a.commandId===req.commandId).length,1);assert.throws(()=>r.service.command(r.operator,{...req,data:{value:false}}),/reutilizado/);assert.equal(r.service.result(r.operator,req.commandId).status,'applied');assert.throws(()=>r.service.result(r.maintenance,req.commandId),/desconocido/);});
test('two clients cannot silently overwrite a stale configuration revision',()=>{const r=rig(),o=r.obj('input',o=>o.binding==='Process.Setpoint'),first=r.request(o,'write',{value:60},0),other=r.request(o,'write',{value:70},0);r.service.command(r.operator,first);assert.throws(()=>r.service.command(r.maintenance,other),/cambiaron/);assert.equal(r.service.state.values['Process.Setpoint'],60);});
test('recipe batch is validated atomically and bound to version',()=>{const r=rig(),o=r.obj('recipes'),recipe=r.service.state.recipes[0],before={...r.service.state.values};recipe.values['Process.Setpoint']=500;assert.throws(()=>r.service.command(r.operator,r.request(o,'recipe.apply',{id:recipe.id,version:recipe.version})),/mayor/);assert.deepEqual(r.service.state.values,before);r.service.state.recipes.find(x=>x.id===recipe.id).values['Process.Setpoint']=65;const out=r.service.command(r.operator,r.request(o,'recipe.apply',{id:recipe.id,version:recipe.version}));assert.equal(out.applied,true);assert.equal(r.service.state.values['Process.Setpoint'],65);assert.throws(()=>r.service.command(r.operator,r.request(o,'recipe.apply',{id:recipe.id,version:0})),/receta cambió/);});
test('recipe editing has distinct roles and may not reach arbitrary RW tags',()=>{const r=rig(),o=r.obj('recipes'),data={id:null,version:0,name:'Nueva',values:{'Process.Setpoint':70}};assert.throws(()=>r.service.command(r.operator,r.request(o,'recipe.save',data)),/Permiso/);const out=r.service.command(r.maintenance,r.request(o,'recipe.save',data));assert.equal(out.result.version,1);assert.throws(()=>r.service.command(r.maintenance,r.request(o,'recipe.save',{...data,values:{'Machine.Running':true}})),/Parámetro no autorizado/);});
test('alarms are captured without a browser; ACK does not clear or reset',()=>{const r=rig();r.service.setSource({'Machine.Fault':true});const occurrence=r.service.state.alarmRows.find(a=>a.active),o=r.obj('alarms');assert.ok(occurrence);r.service.command(r.operator,r.request(o,'alarm.ack',{eventId:occurrence.id}));assert.equal(r.service.state.values['Machine.Fault'],true);assert.equal(r.service.state.alarmRows[0].active,true);r.service.setSource({'Machine.Fault':false});r.service.setSource({'Machine.Fault':true});assert.equal(r.service.state.alarmRows.length,2);assert.notEqual(r.service.state.alarmRows[1].id,occurrence.id);assert.equal(r.service.state.alarmRows[1].ack,false);});
test('hysteresis and activation/clear delays operate on source samples',()=>{const r=rig(p=>{p.alarms=[{...p.alarms[1],hysteresis:5,onDelayMs:100,offDelayMs:200}];});r.service.setSource({'Process.Level':85});assert.equal(r.service.state.alarmRows.length,0);r.advance(100);assert.equal(r.service.state.alarmRows[0].active,true);r.service.setSource({'Process.Level':78});r.advance(500);assert.equal(r.service.state.alarmRows[0].active,true);r.service.setSource({'Process.Level':74});r.advance(199);assert.equal(r.service.state.alarmRows[0].active,true);r.advance(1);assert.equal(r.service.state.alarmRows[0].active,false);});
test('missing source never clears alarms; event cursor recovers retained snapshot',()=>{const r=rig(p=>p.records.retention=100);r.service.setSource({'Machine.Fault':true});r.service.setSource({},false);r.advance(1000);assert.equal(r.service.state.alarmRows[0].active,true);const first=r.service.events(r.operator,{epoch:''});assert.ok(first.reset);for(let i=0;i<110;i++)r.service.transaction(()=>r.service.audit(null,'event','test',null,i,'observed'));const next=r.service.events(r.operator,{epoch:first.epoch,after:0});assert.ok(next.gap);assert.ok(next.snapshot.alarms[0].active);assert.ok(next.dropped>0);});
test('polling does not prevent server-side idle expiration',()=>{const r=rig(p=>p.security.idleSeconds=15);r.service.read(r.operator,['Machine.Running']);r.advance(15001);assert.throws(()=>r.service.read(r.operator,['Machine.Running']),/caducada/);assert.throws(()=>r.service.command(r.operator,r.request(r.obj('button',o=>o.action==='write'),'write',{value:true})),/Identif/);});
test('storage failure rolls back an entire command and blocks unconfirmed operations',()=>{let fail=false;const r=rig(()=>{},{persist:()=>{if(fail)throw new Error('disk full');}}),o=r.obj('input',o=>o.binding==='Process.Setpoint'),before=r.service.state.values['Process.Setpoint'];fail=true;assert.throws(()=>r.service.command(r.operator,r.request(o,'write',{value:66})),/disk full/);assert.equal(r.service.state.values['Process.Setpoint'],before);assert.equal(r.service.storageGood,false);});
test('restored operational recipes survive UI package reload, sessions do not',()=>{const r=rig(),o=r.obj('recipes'),out=r.service.command(r.maintenance,r.request(o,'recipe.save',{name:'Custom',version:0,values:{'Process.Setpoint':44}}));const restored=new MachineService(r.p,{state:r.service.state});assert.equal(restored.state.recipes.find(x=>x.id===out.result.id).values['Process.Setpoint'],44);assert.equal(restored.sessions.size,0);assert.notEqual(restored.state.epoch,r.service.state.epoch);});
