'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const crypto=require('node:crypto'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
require('../core.js');const legacyDemo=NXCore.demoProject();
for(const f of ['model','service','data','exporter','transport'])require('../'+f+'.js');
const C=NXCore,{MachineService}=NXService;
function setup(change=()=>{}){const p=C.demoProject();change(p);let now=100000;const engine=new MachineService(p,{clock:()=>now});const token=role=>engine.newSession({id:role,name:role,role}).token;let seq=0;return {p,engine,token,advance:n=>now+=n,request:(o,action,data={},revision=engine.state.revision)=>({commandId:'test-command-'+(++seq),elementId:o.elementId||o.id,policyDigest:engine.hash,expectedRevision:revision,action,data})};}
const find=(p,predicate)=>[...C.policyObjects(p).values()].find(predicate);
const start=p=>find(p,o=>o.kind==='button'&&o.text==='MARCHA');
const input=p=>find(p,o=>o.kind==='input'&&o.binding==='Process.Setpoint');
const recipeElement=p=>find(p,o=>o.kind==='recipes');
const alarmElement=p=>find(p,o=>o.kind==='alarms');
function readZip(bytes){const buffer=Buffer.from(bytes),files={};let at=0;while(buffer.readUInt32LE(at)===0x04034b50){const size=buffer.readUInt32LE(at+18),n=buffer.readUInt16LE(at+26),extra=buffer.readUInt16LE(at+28),name=buffer.subarray(at+30,at+30+n).toString();at+=30+n+extra;files[name]=buffer.subarray(at,at+size);at+=size;}return files;}
const sources=()=>Object.fromEntries(['style.css',...NXExporter.runtimeFiles].map(f=>[f,fs.readFileSync(path.join(__dirname,'..',f),'utf8')]));

test('v1 migration preserves original and validates v2',()=>{const original=JSON.stringify(legacyDemo),p=C.migrate(legacyDemo);assert.equal(JSON.stringify(legacyDemo),original);assert.equal(p.schemaVersion,2);assert.equal(p.migration.from,1);assert.deepEqual(C.validate(p),[]);assert.deepEqual(C.validate(C.demoProject()),[]);assert.deepEqual(C.validate(C.newProject()),[]);});
test('SHA256 implementation agrees with Node on known vectors and Unicode',()=>{for(const s of ['', 'abc','máquina 🚀','x'.repeat(1000)])assert.equal(C.digest(s),crypto.createHash('sha256').update(s).digest('hex'));});
test('policy digest changes for permissions but not network origin',()=>{const p=C.demoProject(),hash=C.policyDigest(p);p.connection.baseUrl='https://example.test';assert.equal(C.policyDigest(p),hash);start(p);p.screens[0].objects.find(o=>o.text==='MARCHA').operateRoles=['admin'];assert.notEqual(C.policyDigest(p),hash);});
test('project rejects credentials and executable content',()=>{const p=C.demoProject();p.security.password='not-a-real-password';assert.ok(C.validate(p).some(x=>x.includes('credenciales')));assert.throws(()=>C.parseProject('{"__proto__":{}}'));});
test('Sysmac text import preserves STRING length and read-only default',()=>{const vars=C.importVariables('Name\tData Type\tComment\nBatch.Name\tSTRING[80]\tProducto');assert.equal(vars[0].maxLength,80);assert.equal(vars[0].access,'R');assert.throws(()=>C.typed({...vars[0],maxLength:3},'1234'));});
test('subscriptions include screen/master/popups/globals without duplicates',()=>{const p=C.demoProject(),s=p.screens[0];p.variables.push({name:'Hidden',type:'BOOL',access:'R',initial:false,rateMs:1000,global:true,maxLength:255});const vars=C.dependencies(p,s.id,[],'operator').map(v=>v.name);assert.ok(vars.includes('Hidden'));assert.ok(vars.includes('Machine.Running'));assert.ok(!vars.includes('Machine.Fault'));assert.equal(vars.length,new Set(vars).size);const opener=s.objects.find(o=>o.action==='popup');const all=C.dependencies(p,s.id,[{id:opener.targetScreen,bindings:opener.popupBindings,context:opener.id}],'operator');assert.equal(all.filter(v=>v.name==='Machine.Running').length,1);});
test('faceplate policies resolve slot names per opener',()=>{const p=C.demoProject(),opener=p.screens[0].objects.find(o=>o.action==='popup'),items=[...C.policyObjects(p).values()].filter(o=>o.elementId.startsWith(opener.id+'::'));assert.ok(items.length);assert.ok(items.some(o=>o.binding==='Machine.Running'));assert.ok(items.every(o=>!o.binding.startsWith('$')));});
test('roles are nonhierarchical and scope excludes trends',()=>{assert.equal(C.roleAllowed(['maintenance'],'operator'),false);assert.equal(C.roleAllowed(['*'],null),true);assert.ok(!C.KINDS.includes('trend'));assert.ok(!C.KINDS.includes('driver'));});
test('invalid bindings and role references block export',()=>{const p=C.demoProject();p.screens[0].objects[0].operateRoles=['nonexistent'];assert.ok(C.validate(p).length);const q=C.demoProject();q.screens[0].objects.find(o=>o.kind==='lamp').binding='unknown';assert.ok(C.validate(q).length);});

test('anonymous and observer cannot operate, operator can',()=>{const f=setup(),o=start(f.p),req=f.request(o,'write',{value:true});assert.throws(()=>f.engine.command('',req));const observer=f.token('observer');assert.throws(()=>f.engine.command(observer,req),e=>e.status===403);const op=f.token('operator');const response=f.engine.command(op,f.request(o,'write',{value:true}));assert.equal(response.status,'applied');assert.equal(f.engine.state.values['Machine.Running'],true);});
test('installed button action/value and policy cannot be overridden',()=>{const f=setup(),token=f.token('operator'),o=start(f.p);assert.throws(()=>f.engine.command(token,f.request(o,'write',{value:false})));const req=f.request(o,'write',{value:true});req.policyDigest='forged';assert.throws(()=>f.engine.command(token,req),e=>e.code==='POLICY_MISMATCH');assert.equal(f.engine.state.values['Machine.Running'],false);});
test('invalid numeric value rejected without changing source',()=>{const f=setup(),token=f.token('operator');assert.throws(()=>f.engine.command(token,f.request(input(f.p),'write',{value:101})));assert.equal(f.engine.state.values['Process.Setpoint'],55);});
test('enable condition enforced by installed service',()=>{const f=setup(p=>p.screens[0].objects.find(o=>o.text==='MARCHA').enabledBinding='Machine.Fault'),token=f.token('operator');assert.throws(()=>f.engine.command(token,f.request(start(f.p),'write',{value:true})),e=>e.code==='INTERLOCK');});
test('concurrent revision prevents stale second client overwrite',()=>{const f=setup(),a=f.token('operator'),b=f.token('maintenance'),first=f.request(input(f.p),'write',{value:60}),second=f.request(input(f.p),'write',{value:70});f.engine.command(a,first);assert.throws(()=>f.engine.command(b,second),e=>e.code==='REVISION_CONFLICT');assert.equal(f.engine.state.values['Process.Setpoint'],60);});
test('same command is idempotent, conflicting replay is rejected',()=>{const f=setup(),token=f.token('operator'),req=f.request(start(f.p),'write',{value:true});const response=f.engine.command(token,req),revision=f.engine.state.revision;assert.deepEqual(f.engine.command(token,req),response);assert.equal(f.engine.state.revision,revision);assert.throws(()=>f.engine.command(token,{...req,data:{value:false}}),e=>e.code==='ID_CONFLICT');});
test('command outcome lookup is restricted to originating user',()=>{const f=setup(),a=f.token('operator'),b=f.token('maintenance'),req=f.request(start(f.p),'write',{value:true});f.engine.command(a,req);assert.equal(f.engine.result(a,req.commandId).status,'applied');assert.throws(()=>f.engine.result(b,req.commandId));assert.throws(()=>f.engine.result(a,'unknown'));});
test('recipe applies complete set and records active version',()=>{const f=setup(),token=f.token('operator'),r=f.p.recipes[1];f.engine.command(token,f.request(recipeElement(f.p),'recipe.apply',{id:r.id,version:r.version}));assert.equal(f.engine.state.values['Process.Setpoint'],75);assert.equal(f.engine.state.values['Product.Name'],'Formato B');assert.equal(f.engine.state.activeRecipe.id,r.id);});
test('recipe invalid late field rolls back all parameters',()=>{const f=setup(),token=f.token('operator'),r=f.engine.state.recipes[1],before=C.copy(f.engine.state.values);r.values['Product.Name']='x'.repeat(300);assert.throws(()=>f.engine.command(token,f.request(recipeElement(f.p),'recipe.apply',{id:r.id,version:r.version})));assert.deepEqual(f.engine.state.values,before);});
test('recipe edit requires separate role and validates whitelist/version',()=>{const f=setup(),op=f.token('operator'),maint=f.token('maintenance'),o=recipeElement(f.p),r=f.p.recipes[0],data={id:r.id,version:r.version,name:'Actualizada',values:r.values};assert.throws(()=>f.engine.command(op,f.request(o,'recipe.save',data)));const result=f.engine.command(maint,f.request(o,'recipe.save',data));assert.equal(result.result.version,2);assert.throws(()=>f.engine.command(maint,f.request(o,'recipe.save',data)),e=>e.code==='RECIPE_CONFLICT');assert.throws(()=>f.engine.command(maint,f.request(o,'recipe.save',{name:'Escalada',values:{'Machine.Running':true}})));});
test('alarms captured without polling screen; ACK not clear condition',()=>{const f=setup(),token=f.token('operator');f.engine.setSource({'Machine.Fault':true});const row=f.engine.state.alarmRows[0];assert.ok(row.active);f.engine.command(token,f.request(alarmElement(f.p),'alarm.ack',{eventId:row.id}));assert.equal(f.engine.state.alarmRows[0].ack,true);assert.equal(f.engine.state.values['Machine.Fault'],true);assert.equal(f.engine.state.alarmRows[0].active,true);});
test('new alarm occurrence has a distinct id',()=>{const f=setup();f.engine.setSource({'Machine.Fault':true});const id=f.engine.state.alarmRows[0].id;f.engine.setSource({'Machine.Fault':false});f.engine.setSource({'Machine.Fault':true});assert.equal(f.engine.state.alarmRows.length,2);assert.notEqual(f.engine.state.alarmRows[1].id,id);});
test('alarm activation/clear delays and hysteresis use service clock',()=>{const f=setup(p=>{const a=p.alarms[1];a.hysteresis=5;a.onDelayMs=100;a.offDelayMs=100;});f.engine.setSource({'Process.Level':90});assert.equal(f.engine.state.alarmRows.length,0);f.advance(100);f.engine.tick();assert.equal(f.engine.state.alarmRows.length,1);f.engine.setSource({'Process.Level':78});f.advance(100);f.engine.tick();assert.ok(f.engine.state.alarmRows[0].active);f.engine.setSource({'Process.Level':70});assert.ok(f.engine.state.alarmRows[0].active);f.advance(100);f.engine.tick();assert.equal(f.engine.state.alarmRows[0].active,false);});
test('silence does not acknowledge or reset an active alarm',()=>{const f=setup(),token=f.token('operator');f.engine.setSource({'Machine.Fault':true});const r=f.engine.state.alarmRows[0];f.engine.command(token,f.request(alarmElement(f.p),'alarm.silence',{eventId:r.id}));assert.equal(f.engine.state.alarmRows[0].silenced,true);assert.equal(f.engine.state.alarmRows[0].ack,false);assert.equal(f.engine.state.alarmRows[0].active,true);});
test('event cursor reports retention gap',()=>{const f=setup(p=>p.records.retention=100);const first=f.engine.events('',{});for(let i=0;i<120;i++)f.engine.transaction(()=>f.engine.event('test',{i}));const result=f.engine.events('',{epoch:first.epoch,after:0});assert.equal(result.gap,true);assert.ok(result.dropped>0);assert.ok(result.snapshot);});
test('polling does not extend session idle expiration',()=>{const f=setup(p=>{p.security.idleSeconds=15;p.security.maxSessionSeconds=30;}),token=f.token('operator');f.advance(14000);f.engine.read(token,['Machine.Running']);f.advance(1001);assert.throws(()=>f.engine.read(token,['Machine.Running']),e=>e.code==='SESSION_EXPIRED');});
test('logout and user invalidation revoke sessions',()=>{const f=setup(),a=f.token('operator'),b=f.token('maintenance');f.engine.logout(a);assert.throws(()=>f.engine.session(a,true));f.engine.invalidateUser('maintenance');assert.throws(()=>f.engine.session(b,true));});
test('storage failure rolls back command and discloses unavailability',()=>{const f=setup(),token=f.token('operator');f.engine.persist=()=>{throw new Error('storage full');};assert.throws(()=>f.engine.command(token,f.request(input(f.p),'write',{value:70})));assert.equal(f.engine.state.values['Process.Setpoint'],55);assert.equal(f.engine.storageGood,false);});
test('source lost blocks writes and does not clear active alarms',()=>{const f=setup(),token=f.token('operator');f.engine.setSource({'Machine.Fault':true});f.engine.setSource({},false);assert.throws(()=>f.engine.command(token,f.request(start(f.p),'write',{value:true})));assert.equal(f.engine.state.alarmRows[0].active,true);});
test('restored recipes and audit survive UI reload but sessions do not',()=>{const f=setup(),token=f.token('maintenance'),r=f.p.recipes[0];f.engine.command(token,f.request(recipeElement(f.p),'recipe.save',{id:r.id,version:1,name:'Operativa',values:r.values}));const next=C.copy(f.p);next.name='Interfaz actualizada';const restored=new MachineService(next,{state:f.engine.state});assert.equal(restored.state.recipes[0].name==='Operativa'||restored.state.recipes[1].name==='Operativa',true);assert.ok(restored.state.audit.length);assert.throws(()=>restored.session(token,true));assert.notEqual(restored.state.epoch,f.engine.state.epoch);});

test('single export contains full runtime without external script resources',async()=>{const p=C.demoProject(),out=await NXExporter.build(p,'single',sources());assert.ok(out.files['SD/index.html'].includes('hmiRuntime'));assert.ok(!out.files['SD/index.html'].includes('<script src='));assert.equal(JSON.parse(out.files['Engineering/manifest.json']).hardwareValidated,false);assert.equal(JSON.parse(out.files['Engineering/operation-policy.json']).policyDigest,C.policyDigest(p));assert.equal(Object.keys(out.files).filter(x=>x.startsWith('SD/')).length,1);});
test('split export separates views and binary assets with stable build',async()=>{const p=C.demoProject(),data=Buffer.from([0,255,1,127]);p.assets.push({id:C.id(),name:'test',data:'data:image/png;base64,'+data.toString('base64'),width:1,height:1});const a=await NXExporter.build(p,'split',sources()),b=await NXExporter.build(p,'split',sources());assert.equal(a.buildId,b.buildId);const files=readZip(a.zip),asset=Object.keys(files).find(n=>n.endsWith('.png'));assert.deepEqual(files[asset],data);const views=Object.keys(files).filter(n=>n.includes('/views/'));assert.equal(views.length,C.allViews(p).length);assert.ok(a.files['SD/index.html'].includes('hash'));});
test('export escapes inline project text and rejects incomplete bindings',async()=>{const p=C.demoProject();p.name='</script><script>attack()</script>';const result=await NXExporter.build(p,'single',sources());assert.ok(!result.files['SD/index.html'].includes('<script>attack()'));p.screens[0].objects.push(C.newObject('lamp'));await assert.rejects(NXExporter.build(p,'single',sources()));});
test('CSV and XLSX values cannot turn into formula code',()=>{const rows=[['Name','Value'],['=SUM(1,2)',2],['@macro',-3]];assert.match(NXData.csv(rows),/'=SUM/);const files=readZip(NXData.xlsx(rows,'Datos'));const sheet=files['xl/worksheets/sheet1.xml'].toString();assert.ok(!sheet.includes('<f>'));assert.ok(sheet.includes('t="inlineStr"'));assert.ok(sheet.includes('<v>-3</v>'));});

test('HTTP reference bench enforces sessions, roles, private paths and durable audit',async()=>{const {createBench,atomicFile,hashPassword}=require('../server/reference.cjs');const dir=fs.mkdtempSync(path.join(os.tmpdir(),'hmi-v2-http-')),privateDir=path.join(dir,'private'),publicDir=path.join(dir,'SD');fs.mkdirSync(publicDir);fs.writeFileSync(path.join(publicDir,'index.html'),'reference test');const p=C.demoProject(),password=crypto.randomBytes(18).toString('hex'),hash=await hashPassword(password);atomicFile(path.join(privateDir,'users.json'),[{id:'admin',name:'Admin',role:'admin',...hash},{id:'viewer',name:'Viewer',role:'observer',...hash}]);const bench=createBench({project:p,privateDir,publicDir,port:0});try{const {url}=await bench.start();const post=async(route,data,token='',headers={})=>{const response=await fetch(url+'/api/hmi/'+route,{method:'POST',headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{}),...headers},body:JSON.stringify(data)});return {status:response.status,data:await response.json()};};assert.equal((await (await fetch(url+'/api/hmi/capabilities')).json()).deviceMode,'reference-bench');assert.equal((await post('session/login',{username:'admin',password:'wrong'})).status,401);const auth=await post('session/login',{username:'admin',password});assert.equal(auth.status,200);const token=auth.data.token;const users=await post('users',{action:'list'},token);assert.equal(users.status,200);assert.ok(!JSON.stringify(users.data).includes(hash.hash));const viewer=(await post('session/login',{username:'viewer',password})).data.token;const req={commandId:'http-test-command',policyDigest:bench.engine.hash,elementId:start(p).id,action:'write',expectedRevision:0,data:{value:true}};assert.equal((await post('command',req,viewer)).status,403);assert.equal((await post('command',{...req,commandId:'http-test-command-2'},token)).status,200);assert.equal((await post('read',{names:['Machine.Running'],policyDigest:bench.engine.hash},token)).data.values['Machine.Running'],true);assert.equal((await post('session/touch',{},token,{Origin:'https://evil.example'})).status,403);fs.symlinkSync(path.join(privateDir,'users.json'),path.join(publicDir,'leak.json'));assert.equal((await fetch(url+'/leak.json')).status,403);assert.equal((await fetch(url+'/server/reference.cjs')).status,404);assert.equal((await post('users',{action:'update',id:'admin',role:'observer',disabled:false},token)).status,409);assert.equal((await post('users',{action:'update',id:'viewer',role:'observer',disabled:true},token)).status,200);assert.equal((await post('session/touch',{},viewer)).status,401);const persisted=JSON.parse(fs.readFileSync(path.join(privateDir,'state.json')));assert.ok(persisted.audit.some(r=>r.action==='write'));assert.ok(!JSON.stringify(persisted).includes(password));}finally{await bench.stop();fs.rmSync(dir,{recursive:true,force:true});}});
